/*
AddLexAHK1.ahk

Adds the lexer for AutoHotkey (LexAHK1.cxx) to Scintilla.
The cxx file must be in the same dir as the script, which must be in a dir above the scintilla dir.
The files modified are backed up with a _OLD suffix to the extension.
They are SciLexer.h and Catalogue.cxx

// by Philippe Lhoste <PhiLho(a)GMX.net> http://Phi.Lho.free.fr
// File/Project history:
 1.02.000 -- 2010/09/03 (PL) -- Update, for Scintilla 2.21
 1.01.000 -- 2009/09/09 (PL) -- Update, for Scintilla 2.01
 1.00.000 -- 2008/07/01 (PL) -- Finished, at least!
 0.00.000 -- 2007/12/06 (PL) -- Creation.
*/
/* Copyright notice: For details, see the following file:
http://Phi.Lho.free.fr/softwares/PhiLhoSoft/PhiLhoSoftLicence.txt
This program is distributed under the zlib/libpng license.
Copyright (c) 2008-2010 Philippe Lhoste / PhiLhoSoft
*/
#SingleInstance Force

#NoEnv

; I have this directory structure: someDir\SciTE\vx.xx\scintilla | scite
; The script is put in SciTE dir
; Adjust the following lines depending on your settings
sciteVersion = v2.21
scintillaDir = %sciteVersion%\scintilla
SetWorkingDir %A_ScriptDir%

; For Catalogue.cxx (was KeyWords.cxx in 2.12 and, in previous versions of Scintilla, for SciLexer.h too)
endOfCodeMarkCat = //--Autogenerated -- end
; Since 1.77 or 1.78, for SciLexer.h
endOfCodeMarkSL = /* --Autogenerated -- end

;-- Copy the lexer at the proper place

FileCopy LexAHK1.cxx, %scintillaDir%\lexers

;-- Update the list of lexers

sciLexerFile = %scintillaDir%\include\SciLexer.h
FileRead source, %sciLexerFile%

; The line after the last defined lexer
lastLexer = #define SCLEX_AUTOMATIC
; Get current number of last defined lexer
RegExMatch(source, "#define SCLEX_.*? (\d+)\r\n" . lastLexer, lastLexNb)
; We go just after it!
lexNb := lastLexNb1 + 1
; And add it
StringReplace source, source, %lastLexer%, #define SCLEX_AHK1 %lexNb%`r`n%lastLexer%

; The lexer states
lexStates =
(Join`r`n
#define SCE_AHK_DEFAULT 0
#define SCE_AHK_COMMENTLINE 1
#define SCE_AHK_COMMENTBLOCK 2
#define SCE_AHK_ESCAPE 3
#define SCE_AHK_SYNOPERATOR 4
#define SCE_AHK_EXPOPERATOR 5
#define SCE_AHK_STRING 6
#define SCE_AHK_NUMBER 7
#define SCE_AHK_IDENTIFIER 8
#define SCE_AHK_VARREF 9
#define SCE_AHK_LABEL 10
#define SCE_AHK_WORD_CF 11
#define SCE_AHK_WORD_CMD 12
#define SCE_AHK_WORD_FN 13
#define SCE_AHK_WORD_DIR 14
#define SCE_AHK_WORD_KB 15
#define SCE_AHK_WORD_VAR 16
#define SCE_AHK_WORD_SP 17
#define SCE_AHK_WORD_UD 18
#define SCE_AHK_VARREFKW 19
#define SCE_AHK_ERROR 20
)
StringReplace source, source, %endOfCodeMarkSL%, %lexStates%`r`n%endOfCodeMarkSL%

; Keep just in case
FileMove %sciLexerFile%, %sciLexerFile%_OLD
; And put out version...
FileAppend %source%, %sciLexerFile%

;-- Update the lexer loader

scCatFile = %scintillaDir%\src\Catalogue.cxx
FileRead source, %scCatFile%

StringReplace source, source, `r`n`r`n%endOfCodeMarkCat%, `r`n`tLINK_LEXER(lmAHK1);`r`n`r`n%endOfCodeMarkCat%

; Keep just in case
FileMove %scCatFile%, %scCatFile%_OLD
; And put out version...
FileAppend %source%, %scCatFile%

;!!! You must also add the LexAHK1.cxx file to your project (depending on your compiler/IDE).
MsgBox 64, AddLexAHK1, Done!
