/* Copyright 2006 Google */ var tn_=true,tn_a=null,tn_b=false;function tn_aa(a){if(a in tn_ba)return tn_ba[a];return tn_ba[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var tn_ba={},tn_ca={ua:function(a){return a.document.body.scrollTop},va:function(a){return a.document.documentElement.scrollTop},W:function(a){return a.pageYOffset}},tn_da={ua:function(a){return a.document.body.scrollLeft},va:function(a){return a.document.documentElement.scrollLeft},W:function(a){return a.pageXOffset}};
function tn_ea(a,b){try{if(tn_aa("safari")||tn_aa("konqueror"))return b.W(a);else if(!window.opera&&"compatMode"in a.document&&a.document.compatMode=="CSS1Compat")return b.va(a);else if(tn_aa("msie")&&!window.opera)return b.ua(a)}catch(c){}return b.W(a)};function tn_c(a,b,c){this.x=a;this.y=b;this.coordinateFrame=c||tn_a}tn_c.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};tn_c.prototype.clone=function(){return new tn_c(this.x,this.y,this.coordinateFrame)};function tn_fa(a,b){this.dx=a;this.dy=b}tn_fa.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};function tn_d(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.coordinateFrame=e||tn_a}
tn_d.prototype.contains=function(a){return this.x<=a.x&&a.x<this.x+this.w&&this.y<=a.y&&a.y<this.y+this.h};tn_d.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};tn_d.prototype.clone=function(){return new tn_d(this.x,this.y,this.w,this.h,this.coordinateFrame)};function tn_ga(a){function b(h){for(var j=a.offsetParent;j&&j.offsetParent;j=j.offsetParent){if(j.scrollLeft)h.x-=j.scrollLeft;if(j.scrollTop)h.y-=j.scrollTop}}if(!a)return tn_a;var c;c=a.ownerDocument&&a.ownerDocument.parentWindow?a.ownerDocument.parentWindow:a.ownerDocument&&a.ownerDocument.defaultView?a.ownerDocument.defaultView:window;if(a.getBoundingClientRect){var d=a.getBoundingClientRect();return new tn_d(d.left+tn_ea(c,tn_da),d.top+tn_ea(c,tn_ca),d.right-d.left,d.bottom-d.top,c)}if(a.ownerDocument&&
a.ownerDocument.getBoxObjectFor){d=a.ownerDocument.getBoxObjectFor(a);c=new tn_d(d.x,d.y,d.width,d.height,c);b(c);return c}for(var e=d=0,f=a;f.offsetParent;f=f.offsetParent){d+=f.offsetLeft;e+=f.offsetTop}c=new tn_d(d,e,a.offsetWidth,a.offsetHeight,c);b(c);return c};var tn_e=function(){for(var a=[" ","\u0120",-1,"!","\u0120",-1,"\u0120","\u0120",0,"\u0121","\u0120",-1,"\u0121","\u0120|\u0121",0,"\u0122","\u0120|\u0121",-1,"\u0120","[\u0120]",0,"\u0121","[\u0120]",-1,"\u0121","[\u0120\u0121]",0,"\u0122","[\u0120\u0121]",-1,"\u0121","[\u0120-\u0121]",0,"\u0122","[\u0120-\u0121]",-1],b=0;b<a.length;b+=3)if(a[b].search(RegExp(a[b+1]))!=a[b+2])return tn_b;return tn_}(),tn_ha=tn_e?"A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u00ff\u0100-\u0131\u0134-\u013e\u0141-\u0148\u014a-\u017e\u0180-\u01c3\u01cd-\u01f0\u01f4-\u01f5\u01fa-\u0217\u0250-\u02a8\u02bb-\u02c1\u0386\u0388-\u038a\u038c\u038e-\u03a1\u03a3-\u03ce\u03d0-\u03d6\u03da\u03dc\u03de\u03e0\u03e2-\u03f3\u0401-\u040c\u040e-\u044f\u0451-\u045c\u045e-\u0481\u0490-\u04c4\u04c7-\u04c8\u04cb-\u04cc\u04d0-\u04eb\u04ee-\u04f5\u04f8-\u04f9\u0531-\u0556\u0559\u0561-\u0586\u05d0-\u05ea\u05f0-\u05f2\u0621-\u063a\u0641-\u064a\u0671-\u06b7\u06ba-\u06be\u06c0-\u06ce\u06d0-\u06d3\u06d5\u06e5-\u06e6\u0905-\u0939\u093d\u0958-\u0961\u0985-\u098c\u098f-\u0990\u0993-\u09a8\u09aa-\u09b0\u09b2\u09b6-\u09b9\u09dc-\u09dd\u09df-\u09e1\u09f0-\u09f1\u0a05-\u0a0a\u0a0f-\u0a10\u0a13-\u0a28\u0a2a-\u0a30\u0a32-\u0a33\u0a35-\u0a36\u0a38-\u0a39\u0a59-\u0a5c\u0a5e\u0a72-\u0a74\u0a85-\u0a8b\u0a8d\u0a8f-\u0a91\u0a93-\u0aa8\u0aaa-\u0ab0\u0ab2-\u0ab3\u0ab5-\u0ab9\u0abd\u0ae0\u0b05-\u0b0c\u0b0f-\u0b10\u0b13-\u0b28\u0b2a-\u0b30\u0b32-\u0b33\u0b36-\u0b39\u0b3d\u0b5c-\u0b5d\u0b5f-\u0b61\u0b85-\u0b8a\u0b8e-\u0b90\u0b92-\u0b95\u0b99-\u0b9a\u0b9c\u0b9e-\u0b9f\u0ba3-\u0ba4\u0ba8-\u0baa\u0bae-\u0bb5\u0bb7-\u0bb9\u0c05-\u0c0c\u0c0e-\u0c10\u0c12-\u0c28\u0c2a-\u0c33\u0c35-\u0c39\u0c60-\u0c61\u0c85-\u0c8c\u0c8e-\u0c90\u0c92-\u0ca8\u0caa-\u0cb3\u0cb5-\u0cb9\u0cde\u0ce0-\u0ce1\u0d05-\u0d0c\u0d0e-\u0d10\u0d12-\u0d28\u0d2a-\u0d39\u0d60-\u0d61\u0e01-\u0e2e\u0e30\u0e32-\u0e33\u0e40-\u0e45\u0e81-\u0e82\u0e84\u0e87-\u0e88\u0e8a\u0e8d\u0e94-\u0e97\u0e99-\u0e9f\u0ea1-\u0ea3\u0ea5\u0ea7\u0eaa-\u0eab\u0ead-\u0eae\u0eb0\u0eb2-\u0eb3\u0ebd\u0ec0-\u0ec4\u0f40-\u0f47\u0f49-\u0f69\u10a0-\u10c5\u10d0-\u10f6\u1100\u1102-\u1103\u1105-\u1107\u1109\u110b-\u110c\u110e-\u1112\u113c\u113e\u1140\u114c\u114e\u1150\u1154-\u1155\u1159\u115f-\u1161\u1163\u1165\u1167\u1169\u116d-\u116e\u1172-\u1173\u1175\u119e\u11a8\u11ab\u11ae-\u11af\u11b7-\u11b8\u11ba\u11bc-\u11c2\u11eb\u11f0\u11f9\u1e00-\u1e9b\u1ea0-\u1ef9\u1f00-\u1f15\u1f18-\u1f1d\u1f20-\u1f45\u1f48-\u1f4d\u1f50-\u1f57\u1f59\u1f5b\u1f5d\u1f5f-\u1f7d\u1f80-\u1fb4\u1fb6-\u1fbc\u1fbe\u1fc2-\u1fc4\u1fc6-\u1fcc\u1fd0-\u1fd3\u1fd6-\u1fdb\u1fe0-\u1fec\u1ff2-\u1ff4\u1ff6-\u1ffc\u2126\u212a-\u212b\u212e\u2180-\u2182\u3041-\u3094\u30a1-\u30fa\u3105-\u312c\uac00-\ud7a3":
"A-Za-z",tn_ia=tn_e?"\u4e00-\u9fa5\u3007\u3021-\u3029":"",tn_ja=tn_e?"\u0300-\u0345\u0360-\u0361\u0483-\u0486\u0591-\u05a1\u05a3-\u05b9\u05bb-\u05bd\u05bf\u05c1-\u05c2\u05c4\u064b-\u0652\u0670\u06d6-\u06dc\u06dd-\u06df\u06e0-\u06e4\u06e7-\u06e8\u06ea-\u06ed\u0901-\u0903\u093c\u093e-\u094c\u094d\u0951-\u0954\u0962-\u0963\u0981-\u0983\u09bc\u09be\u09bf\u09c0-\u09c4\u09c7-\u09c8\u09cb-\u09cd\u09d7\u09e2-\u09e3\u0a02\u0a3c\u0a3e\u0a3f\u0a40-\u0a42\u0a47-\u0a48\u0a4b-\u0a4d\u0a70-\u0a71\u0a81-\u0a83\u0abc\u0abe-\u0ac5\u0ac7-\u0ac9\u0acb-\u0acd\u0b01-\u0b03\u0b3c\u0b3e-\u0b43\u0b47-\u0b48\u0b4b-\u0b4d\u0b56-\u0b57\u0b82-\u0b83\u0bbe-\u0bc2\u0bc6-\u0bc8\u0bca-\u0bcd\u0bd7\u0c01-\u0c03\u0c3e-\u0c44\u0c46-\u0c48\u0c4a-\u0c4d\u0c55-\u0c56\u0c82-\u0c83\u0cbe-\u0cc4\u0cc6-\u0cc8\u0cca-\u0ccd\u0cd5-\u0cd6\u0d02-\u0d03\u0d3e-\u0d43\u0d46-\u0d48\u0d4a-\u0d4d\u0d57\u0e31\u0e34-\u0e3a\u0e47-\u0e4e\u0eb1\u0eb4-\u0eb9\u0ebb-\u0ebc\u0ec8-\u0ecd\u0f18-\u0f19\u0f35\u0f37\u0f39\u0f3e\u0f3f\u0f71-\u0f84\u0f86-\u0f8b\u0f90-\u0f95\u0f97\u0f99-\u0fad\u0fb1-\u0fb7\u0fb9\u20d0-\u20dc\u20e1\u302a-\u302f\u3099\u309a":
"",tn_ka=tn_e?"0-9\u0660-\u0669\u06f0-\u06f9\u0966-\u096f\u09e6-\u09ef\u0a66-\u0a6f\u0ae6-\u0aef\u0b66-\u0b6f\u0be7-\u0bef\u0c66-\u0c6f\u0ce6-\u0cef\u0d66-\u0d6f\u0e50-\u0e59\u0ed0-\u0ed9\u0f20-\u0f29":"0-9",tn_la=tn_e?"\u00b7\u02d0\u02d1\u0387\u0640\u0e46\u0ec6\u3005\u3031-\u3035\u309d-\u309e\u30fc-\u30fe":"",tn_ma=tn_ha+tn_ia,tn_na=tn_ma+tn_ka+"\\._:"+tn_ja+tn_la+"-",tn_oa="["+tn_ma+"_:]["+tn_na+"]*",tn_pa="&"+tn_oa+";",tn_qa=tn_pa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ra='"(([^<&"]|'+tn_qa+")*)\"|'(([^<&']|"+
tn_qa+")*)'",tn_sa="("+tn_oa+")([ \t\r\n]+)?=([ \t\r\n]+)?("+tn_ra+")",tn_ta=tn_e?":A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd":":A-Z_a-z",tn_ua=tn_ta+(tn_e?"\\.0-9\u00b7\u0300-\u036f\u203f-\u2040-":"\\.0-9-"),tn_va="["+tn_ta+"]["+tn_ua+"]*",tn_wa="&"+tn_va+";",tn_xa=tn_wa+"|&#[0-9]+;|&#x[0-9a-fA-F]+;",tn_ya='"(([^<&"]|'+tn_xa+")*)\"|'(([^<&']|"+tn_xa+")*)'",tn_za="("+tn_va+")([ \t\r\n]+)?=([ \t\r\n]+)?("+
tn_ya+")",tn_Aa=tn_ma+tn_ka+"\\._"+tn_ja+tn_la+"-",tn_Ba="["+tn_ma+"_]["+tn_Aa+"]*";function tn_f(a){a||tn_g("Assertion failed")}function tn_Ca(a,b){var c=a.indexOf(b);if(c==-1)return[a];var d=[];for(d.push(a.substr(0,c));c!=-1;){var e=a.indexOf(b,c+1);e!=-1?d.push(a.substr(c+1,e-c-1)):d.push(a.substr(c+1));c=e}return d}
function tn_Da(a,b){if(b.nodeType==3)return a.createTextNode(b.nodeValue);else if(b.nodeType==4)return a.createCDATASection(b.nodeValue);else if(b.nodeType==1){for(var c=a.createElement(b.nodeName),d=0;d<b.attributes.length;++d){var e=b.attributes[d],f=e.nodeName;e=e.nodeValue;c.setAttribute(f,e)}for(d=b.firstChild;d;d=d.nextSibling){f=arguments.callee(a,d);c.appendChild(f)}return c}else return a.createComment(b.nodeName)}function tn_Ea(){this.keys=[]}tn_Ea.prototype.size=function(){return this.keys.length};
tn_Ea.prototype.add=function(a,b){var c=b||1;if(!this.contains(a)){this[":"+a]=c;this.keys.push(a)}};tn_Ea.prototype.remove=function(a){if(this.contains(a)){delete this[":"+a];tn_Fa(this.keys,a,tn_)}};tn_Ea.prototype.contains=function(a){return typeof this[":"+a]!="undefined"};tn_Ea.prototype.map=function(a){for(var b=0;b<this.keys.length;++b){var c=this.keys[b];a.call(this,c,this[":"+c])}};
tn_Ea.prototype.clear=function(){for(var a=0;a<this.keys.length;++a)delete this[":"+this.keys[a]];this.keys.length=0};function tn_Ga(a,b){for(var c=0;c<a.length;++c)b.call(this,a[c],c)}function tn_Ha(a,b){for(var c=[],d=0;d<a.length;++d)c.push(b(a[d]));return c}function tn_Ia(a){for(var b=0;b<a.length/2;++b){var c=a[b],d=a.length-b-1;a[b]=a[d];a[d]=c}}function tn_Fa(a,b,c){for(var d=0,e=0;e<a.length;++e)if(a[e]===b||c&&a[e]==b){a.splice(e--,1);d++}return d}
function tn_Ja(a,b){for(var c=0;c<b.length;++c)a.push(b[c])}function tn_h(a){if(!a)return"";var b="";if(a.nodeType==3||a.nodeType==4||a.nodeType==2)b+=a.nodeValue;else if(a.nodeType==1||a.nodeType==9||a.nodeType==11)for(var c=0;c<a.childNodes.length;++c)b+=arguments.callee(a.childNodes[c]);return b}function tn_Ka(a,b){var c=[];tn_La(a,c,b);return c.join("")}
function tn_La(a,b,c){if(a.nodeType==3)b.push(tn_Ma(a.nodeValue));else if(a.nodeType==4)c?b.push(a.nodeValue):b.push("<![CDATA["+a.nodeValue+"]]\>");else if(a.nodeType==8)b.push("<!--"+a.nodeValue+"--\>");else if(a.nodeType==1){b.push("<"+tn_Na(a));for(var d=0;d<a.attributes.length;++d){var e=a.attributes[d];e&&e.nodeName&&e.nodeValue&&b.push(" "+tn_Na(e)+'="'+tn_Ma(e.nodeValue).replace(/\"/g,"&quot;")+'"')}if(a.childNodes.length==0)b.push("/>");else{b.push(">");for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],
b,c);b.push("</"+tn_Na(a)+">")}}else if(a.nodeType==9||a.nodeType==11)for(d=0;d<a.childNodes.length;++d)arguments.callee(a.childNodes[d],b,c)}function tn_Na(a){return a.prefix&&a.nodeName.indexOf(a.prefix+":")!=0?a.prefix+":"+a.nodeName:a.nodeName}function tn_Ma(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function tn_Oa(a,b,c){return a.setAttribute(b,c)}function tn_Pa(a,b){return a.appendChild(b)}function tn_Qa(a,b){return a.createTextNode(b)}
function tn_g(a){if(typeof Error!="undefined")throw Error(a||"Assertion Failed");else throw a;};function tn_Ra(a){a=tn_Ca(a,"&");for(var b=a[0],c=1;c<a.length;++c){var d=a[c].indexOf(";");if(d==-1)b+=a[c];else{var e=a[c].substring(0,d);d=a[c].substring(d+1);switch(e){case "lt":e="<";break;case "gt":e=">";break;case "amp":e="&";break;case "quot":e='"';break;case "apos":e="'";break;case "nbsp":e=String.fromCharCode(160);break;default:var f=window.document.createElement("span");f.innerHTML="&"+e+"; ";e=f.childNodes[0].nodeValue.charAt(0)}b+=e+d}}return b}
var tn_Sa=RegExp("^("+tn_oa+")"),tn_Ta=RegExp(tn_sa,"g"),tn_Ua=RegExp("^("+tn_va+")"),tn_Va=RegExp(tn_za,"g");
function tn_Wa(a){var b=/\/$/,c,d;if(a.match(/^<\?xml/))if(a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.0"|'1\.0')/)==5){c=tn_Sa;d=tn_Ta}else if(a.search(/[ \t\r\n]+version([ \t\r\n]+)?=([ \t\r\n]+)?("1\.1"|'1\.1')/)==5){c=tn_Ua;d=tn_Va}else alert("VersionInfo is missing, or unknown version number.");else{c=tn_Sa;d=tn_Ta}var e=new tn_i,f=e,h=[],j=f;h.push(j);var m="";a=tn_Ca(a,"<");for(var l=1;l<a.length;++l){var g=tn_Ca(a[l],">"),i=g[0];g=tn_Ra(g[1]||"");if(m){i=a[l].indexOf(m);if(i!=
-1){var n=a[l].substring(0,i);j.nodeValue+="<"+n;h.pop();j=h[h.length-1];g=a[l].substring(i+m.length);m=""}else{j.nodeValue+="<"+a[l];g=tn_a}}else if(i.indexOf("![CDATA[")==0){n=8;i=a[l].indexOf("]]\>");if(i!=-1){n=a[l].substring(n,i);var k=e.createCDATASection(n);j.appendChild(k)}else{n=a[l].substring(n);g=tn_a;k=e.createCDATASection(n);j.appendChild(k);j=k;h.push(k);m="]]\>"}}else if(i.indexOf("!--")==0){n=3;i=a[l].indexOf("--\>");if(i!=-1){n=a[l].substring(n,i);k=e.createComment(n);j.appendChild(k)}else{n=
a[l].substring(n);g=tn_a;k=e.createComment(n);j.appendChild(k);j=k;h.push(k);m="--\>"}}else if(i.charAt(0)=="/"){h.pop();j=h[h.length-1]}else if(i.charAt(0)!="?")if(i.charAt(0)!="!"){n=i.match(b);k=c.exec(i)[1];k=e.createElement(k);for(var o;o=d.exec(i);){var p=tn_Ra(o[5]||o[7]||"");k.setAttribute(o[1],p)}j.appendChild(k);if(!n){j=k;h.push(k)}}g&&j!=f&&tn_Pa(j,e.createTextNode(g))}return f}
function tn_Xa(a,b,c){var d;if(b){d=b.call(tn_a,a);if(typeof d=="boolean"&&!d)return tn_b}for(var e=a.firstChild;e;e=e.nextSibling)if(e.nodeType==1){d=arguments.callee.call(this,e,b,c);if(typeof d=="boolean"&&!d)return tn_b}if(c){d=c.call(tn_a,a);if(typeof d=="boolean"&&!d)return tn_b}}function tn_j(a,b,c,d){this.attributes=[];this.childNodes=[];tn_j.init.call(this,a,b,c,d)}
tn_j.init=function(a,b,c,d){this.nodeType=a-0;this.nodeName=""+b;this.nodeValue=""+c;this.ownerDocument=d;this.parentNode=this.previousSibling=this.nextSibling=this.lastChild=this.firstChild=tn_a};tn_j.ia=[];
tn_j.recycle=function(a){if(a)if(a.constructor==tn_i)tn_j.recycle(a.documentElement);else if(a.constructor==this){tn_j.ia.push(a);for(var b=0;b<a.attributes.length;++b)tn_j.recycle(a.attributes[b]);for(b=0;b<a.childNodes.length;++b)tn_j.recycle(a.childNodes[b]);a.attributes.length=0;a.childNodes.length=0;tn_j.init.call(a,0,"","",tn_a)}};tn_j.create=function(a,b,c,d){if(tn_j.ia.length>0){var e=tn_j.ia.pop();tn_j.init.call(e,a,b,c,d);return e}else return new tn_j(a,b,c,d)};
tn_j.prototype.appendChild=function(a){if(this.childNodes.length==0)this.firstChild=a;a.previousSibling=this.lastChild;a.nextSibling=tn_a;if(this.lastChild)this.lastChild.nextSibling=a;a.parentNode=this;this.lastChild=a;this.childNodes.push(a)};
tn_j.prototype.replaceChild=function(a,b){if(b!=a)for(var c=0;c<this.childNodes.length;++c)if(this.childNodes[c]==b){this.childNodes[c]=a;c=b.parentNode;b.parentNode=tn_a;a.parentNode=c;c=b.previousSibling;b.previousSibling=tn_a;a.previousSibling=c;if(a.previousSibling)a.previousSibling.nextSibling=a;c=b.nextSibling;b.nextSibling=tn_a;a.nextSibling=c;if(a.nextSibling)a.nextSibling.previousSibling=a;if(this.firstChild==b)this.firstChild=a;if(this.lastChild==b)this.lastChild=a;break}};
tn_j.prototype.insertBefore=function(a,b){if(b!=a)if(b.parentNode==this){a.parentNode&&a.parentNode.removeChild(a);for(var c=[],d=0;d<this.childNodes.length;++d){var e=this.childNodes[d];if(e==b){c.push(a);a.parentNode=this;a.previousSibling=b.previousSibling;b.previousSibling=a;if(a.previousSibling)a.previousSibling.nextSibling=a;a.nextSibling=b;if(this.firstChild==b)this.firstChild=a}c.push(e)}this.childNodes=c}};
tn_j.prototype.removeChild=function(a){for(var b=[],c=0;c<this.childNodes.length;++c){var d=this.childNodes[c];if(d!=a)b.push(d);else{if(d.previousSibling)d.previousSibling.nextSibling=d.nextSibling;if(d.nextSibling)d.nextSibling.previousSibling=d.previousSibling;if(this.firstChild==d)this.firstChild=d.nextSibling;if(this.lastChild==d)this.lastChild=d.previousSibling}}this.childNodes=b};tn_j.prototype.hasAttributes=function(){return this.attributes.length>0};
tn_j.prototype.setAttribute=function(a,b){for(var c=0;c<this.attributes.length;++c)if(this.attributes[c].nodeName==a){this.attributes[c].nodeValue=""+b;return}this.attributes.push(tn_j.create(2,a,b,this))};tn_j.prototype.getAttribute=function(a){for(var b=0;b<this.attributes.length;++b)if(this.attributes[b].nodeName==a)return this.attributes[b].nodeValue;return tn_a};
tn_j.prototype.removeAttribute=function(a){for(var b=[],c=0;c<this.attributes.length;++c)this.attributes[c].nodeName!=a&&b.push(this.attributes[c]);this.attributes=b};tn_j.prototype.getElementsByTagName=function(a){var b=[];tn_Xa(this,function(c){c.nodeName==a&&b.push(c)},tn_a);return b};tn_j.prototype.getElementById=function(a){var b=tn_a;tn_Xa(this,function(c){if(c.getAttribute("id")==a){b=c;return tn_b}},tn_a);return b};
function tn_i(){tn_j.call(this,9,"#document",tn_a,tn_a);this.documentElement=tn_a}tn_i.prototype=new tn_j(9,"#document");tn_i.prototype.clear=function(){tn_j.recycle(this.documentElement);this.documentElement=tn_a};tn_i.prototype.appendChild=function(a){tn_j.prototype.appendChild.call(this,a);this.documentElement=this.childNodes[0]};tn_i.prototype.createElement=function(a){return tn_j.create(1,a,tn_a,this)};
tn_i.prototype.createDocumentFragment=function(){return tn_j.create(11,"#document-fragment",tn_a,this)};tn_i.prototype.createTextNode=function(a){return tn_j.create(3,"#text",a,this)};tn_i.prototype.createAttribute=function(a){return tn_j.create(2,a,tn_a,this)};tn_i.prototype.createComment=function(a){return tn_j.create(8,"#comment",a,this)};tn_i.prototype.createCDATASection=function(a){return tn_j.create(4,"#cdata-section",a,this)};function tn_Ya(a,b){tn_Za(new tn_k(a,b),b)}
function tn_Za(a,b){var c=b.getAttribute("select");if(c){b.removeAttribute("select");tn__a(a,b,c)}else{if(c=b.getAttribute("display"))if(tn_0a(c,a).d())b.removeAttribute("display");else{b.parentNode.removeChild(b);return}if(c=b.getAttribute("values")){b.removeAttribute("values");tn_1a(a,b,c)}if(c=b.getAttribute("transclude")){if(c=tn_2a(c,b.ownerDocument)){b.parentNode.replaceChild(c,b);tn_Za(a,c)}else b.parentNode.removeChild(b);tn_j.recycle(b)}else if(c=b.getAttribute("content")){b.removeAttribute("content");
tn_3a(a,b,c)}else{c=[];for(var d=0;d<b.childNodes.length;++d)b.childNodes[d].nodeType==1&&c.push(b.childNodes[d]);for(d=0;d<c.length;++d)tn_Za(a,c[d])}}}
function tn__a(a,b,c){var d=c.split(/;/),e=tn_0a(d[0],a).c();if(e.length>0){c=[];for(var f=1;f<e.length;++f){var h=tn_Da(b.ownerDocument,b);c.push(h);b.parentNode.insertBefore(h,b)}c.push(b);b=[];for(f=1;f<d.length;++f){var j=d[f],m=0;if(j.charAt(m)=="#"){h="number";m++}else h="text";if(j.charAt(m)=="-"){j="descending";m++}else j="ascending";m=tn_4a(d[f].substr(m));b.push({expr:m,type:h,order:j})}a=a.clone(e[0],0,e);tn_5a(a,b);for(f=0;f<a.z();++f)a.nodelist[f].nodeType==1&&tn_Za(a.clone(a.nodelist[f],
f),c[f])}else b.parentNode.removeChild(b)}function tn_1a(a,b,c){c=c.split(/;/);for(var d=0;d<c.length;++d){var e=c[d].indexOf(":");if(!(e<0)){var f=c[d].substr(0,e);e=tn_0a(c[d].substr(e+1),a);if(f.charAt(0)=="$")a.fa(f.substr(1),e);else f&&tn_Oa(b,f,e.a())}}}
function tn_3a(a,b,c){for(;b.firstChild;)b.removeChild(b.firstChild);a=tn_0a(c,a);if(a.type=="node-set")for(c=0;c<a.value.length;++c){var d=a.value[c];if(d.nodeType==1)for(d=d.firstChild;d;d=d.nextSibling){var e=tn_Da(b.ownerDocument,d);b.appendChild(e)}else if(d.nodeType==2){d=b.ownerDocument.createTextNode(d.nodeValue);b.appendChild(d)}}else{d=tn_Qa(b.ownerDocument,a.a());b.appendChild(d)}}function tn_0a(a,b){var c=tn_4a(a);return c=c.evaluate(b)}
function tn_2a(a,b){var c=b.getElementById(a);if(c)return c=tn_Da(b,c);else return tn_a};function tn_4a(a){tn_6a();var b=tn_7a[a];if(b)return b;if(a.match(/^(\$|@)?\w+$/i)){b=tn_8a(a);return tn_7a[a]=b}if(a.match(/^\w+(\/\w+)*$/i)){b=tn_9a(a);return tn_7a[a]=b}b=a;for(var c=[],d=tn_a,e=tn_a,f=tn_b,h=0,j=0,m=0;!f;){h++;a=a.replace(/^\s*/,"");e=d;for(var l=d=tn_a,g="",i=0;i<tn_$a.length;++i){var n=tn_$a[i].re.exec(a);j++;if(n&&n.length>0&&n[0].length>g.length){l=tn_$a[i];g=n[0];break}}if(l&&(l==tn_ab||l==tn_bb||l==tn_cb||l==tn_db)&&(!e||e.tag==tn_eb||e.tag==tn_fb||e.tag==tn_l||e.tag==tn_gb||
e.tag==tn_hb))l=tn_ib;if(l){a=a.substr(g.length);d={tag:l,match:g,prec:l.prec?l.prec:0,expr:new tn_jb(g)}}else f=tn_;for(;tn_kb(c,d);)m++}c.length!=1&&tn_g("XPath parse error "+b+":\n"+tn_lb(c));n=c[0].expr;return tn_7a[b]=n}var tn_7a={};
function tn_kb(a,b){var c=tn_a;if(a.length>0){var d=a[a.length-1];if(d=tn_mb[d.tag.key])for(var e=0;e<d.length;++e){var f=d[e],h=tn_nb(a,f[1]);if(h.length){c={tag:f[0],rule:f,match:h};c.prec=tn_ob(c);break}}}if(c&&(!b||c.prec>b.prec||b.tag.left&&c.prec>=b.prec)){for(e=0;e<c.match.matchlength;++e)a.pop();d=tn_Ha(c.match,function(j){return j.expr});c.expr=c.rule[3].apply(tn_a,d);a.push(c);c=tn_}else{b&&a.push(b);c=tn_b}return c}
function tn_nb(a,b){var c=a.length,d=b.length,e=[],f=e.matchlength=0;d=d-1;for(c=c-1;d>=0&&c>=0;--d,c-=f){f=0;var h=[];if(b[d]==tn_pb){d-=1;for(e.push(h);c-f>=0&&a[c-f].tag==b[d];){h.push(a[c-f]);f+=1;e.matchlength+=1}}else if(b[d]==tn_qb){d-=1;for(e.push(h);c-f>=0&&f<2&&a[c-f].tag==b[d];){h.push(a[c-f]);f+=1;e.matchlength+=1}}else if(b[d]==tn_rb){d-=1;e.push(h);if(a[c].tag==b[d])for(;c-f>=0&&a[c-f].tag==b[d];){h.push(a[c-f]);f+=1;e.matchlength+=1}else return[]}else if(a[c].tag==b[d]){e.push(a[c]);
f+=1;e.matchlength+=1}else return[];tn_Ia(h);h.expr=tn_Ha(h,function(j){return j.expr})}tn_Ia(e);return d==-1?e:[]}function tn_ob(a){var b=0;if(a.rule)if(a.rule.length>=3&&a.rule[2]>=0)b=a.rule[2];else for(var c=0;c<a.rule[1].length;++c){var d=a.rule[1][c].prec||2;b=Math.max(b,d)}else if(a.tag)b=a.tag.prec||2;else if(a.length)for(c=0;c<a.length;++c){d=tn_ob(a[c]);b=Math.max(b,d)}return b}function tn_lb(a){for(var b="",c=0;c<a.length;++c){if(b)b+="\n";b+=a[c].tag.label}return b}
function tn_k(a,b,c,d,e){this.node=a;this.stylesheet=b||tn_a;this.position=c||0;this.nodelist=d||[a];this.variables={};this.parent=e||tn_a;this.root=e?e.root:this.node.nodeType==9?a:a.ownerDocument}tn_k.prototype.clone=function(a,b,c){return new tn_k(a||this.node,this.stylesheet,typeof b!="undefined"?b:this.position,c||this.nodelist,this)};tn_k.prototype.fa=function(a,b){this.variables[a]=b};
tn_k.prototype.J=function(a){return typeof this.variables[a]!="undefined"?this.variables[a]:this.parent?this.parent.J(a):tn_a};tn_k.prototype.Oa=function(a){this.node=this.nodelist[a];this.position=a};tn_k.prototype.z=function(){return this.nodelist.length};function tn_m(a){this.value=a;this.type="string"}tn_m.prototype.a=function(){return this.value};tn_m.prototype.d=function(){return this.value.length>0};tn_m.prototype.b=function(){return this.value-0};tn_m.prototype.c=function(){tn_g(this)};
function tn_n(a){this.value=a;this.type="boolean"}tn_n.prototype.a=function(){return""+this.value};tn_n.prototype.d=function(){return this.value};tn_n.prototype.b=function(){return this.value?1:0};tn_n.prototype.c=function(){tn_g(this)};function tn_o(a){this.value=a;this.type="number"}tn_o.prototype.a=function(){return""+this.value};tn_o.prototype.d=function(){return!!this.value};tn_o.prototype.b=function(){return this.value-0};tn_o.prototype.c=function(){tn_g(this)};
function tn_p(a){this.value=a;this.type="node-set"}tn_p.prototype.a=function(){return this.value.length==0?"":tn_h(this.value[0])};tn_p.prototype.d=function(){return this.value.length>0};tn_p.prototype.b=function(){return this.a()-0};tn_p.prototype.c=function(){return this.value};function tn_jb(a){this.value=a}tn_jb.prototype.evaluate=function(){return new tn_m(this.value)};function tn_q(){this.absolute=tn_b;this.rootExpr=tn_a;this.steps=[]}tn_q.prototype.j=function(a){this.steps.push(a)};
tn_q.prototype.ca=function(a){this.steps.unshift(a)};tn_q.prototype.evaluate=function(a){var b;b=this.rootExpr?this.rootExpr.evaluate(a).c():this.absolute?[a.root]:[a.node];for(var c=[],d=0;d<b.length;++d){var e=b[d];tn_sb(c,this.steps,0,e,a)}return new tn_p(c)};function tn_sb(a,b,c,d,e){var f=b[c];d=e.clone(d);f=f.evaluate(d).c();for(d=0;d<f.length;++d)c==b.length-1?a.push(f[d]):tn_sb(a,b,c+1,f[d],e)}function tn_r(a,b,c){this.axis=a;this.nodetest=b;this.predicate=c||[]}tn_r.prototype.la=function(a){this.predicate.push(a)};
tn_r.prototype.evaluate=function(a){var b=a.node,c=[];if(this.axis==tn_s.ANCESTOR_OR_SELF){c.push(b);for(b=b.parentNode;b;b=b.parentNode)c.push(b)}else if(this.axis==tn_s.ANCESTOR)for(b=b.parentNode;b;b=b.parentNode)c.push(b);else if(this.axis==tn_s.ATTRIBUTE)tn_Ja(c,b.attributes);else if(this.axis==tn_s.CHILD)tn_Ja(c,b.childNodes);else if(this.axis==tn_s.DESCENDANT_OR_SELF){c.push(b);tn_tb(c,b)}else if(this.axis==tn_s.DESCENDANT)tn_tb(c,b);else if(this.axis==tn_s.FOLLOWING)for(b=b;b;b=b.parentNode)for(var d=
b.nextSibling;d;d=d.nextSibling){c.push(d);tn_tb(c,d)}else if(this.axis==tn_s.FOLLOWING_SIBLING)for(b=b.nextSibling;b;b=b.nextSibling)c.push(b);else if(this.axis==tn_s.NAMESPACE)tn_g("not implemented: axis namespace");else if(this.axis==tn_s.PARENT)b.parentNode&&c.push(b.parentNode);else if(this.axis==tn_s.PRECEDING)for(b=b;b;b=b.parentNode)for(d=b.previousSibling;d;d=d.previousSibling){c.push(d);tn_ub(c,d)}else if(this.axis==tn_s.PRECEDING_SIBLING)for(b=b.previousSibling;b;b=b.previousSibling)c.push(b);
else this.axis==tn_s.SELF?c.push(b):tn_g("ERROR -- NO SUCH AXIS: "+this.axis);d=c;c=[];for(var e=0;e<d.length;++e){b=d[e];this.nodetest.evaluate(a.clone(b,e,d)).d()&&c.push(b)}for(e=0;e<this.predicate.length;++e){d=c;c=[];for(var f=0;f<d.length;++f){b=d[f];this.predicate[e].evaluate(a.clone(b,f,d)).d()&&c.push(b)}}return new tn_p(c)};function tn_vb(){this.value=new tn_n(tn_)}tn_vb.prototype.evaluate=function(){return this.value};function tn_wb(){}
tn_wb.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==1||a.node.nodeType==2)};function tn_xb(){}tn_xb.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==3)};function tn_yb(){}tn_yb.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==8)};function tn_zb(a){this.target=a}tn_zb.prototype.evaluate=function(a){return new tn_n(a.node.nodeType==7&&(!this.target||a.node.nodeName==this.target))};function tn_Ab(a){this.regex=RegExp("^"+a+":");this.nsprefix=a}
tn_Ab.prototype.evaluate=function(a){a=a.node;return new tn_n(this.regex.test(a.nodeName))};function tn_Bb(a){this.name=a}tn_Bb.prototype.evaluate=function(a){a=a.node;return new tn_n(a.nodeName==this.name)};function tn_Cb(a){this.expr=a}tn_Cb.prototype.evaluate=function(a){var b=this.expr.evaluate(a);return b.type=="number"?new tn_n(a.position==b.b()-1):new tn_n(b.d())};function tn_Db(a){this.name=a;this.args=[]}tn_Db.prototype.T=function(a){this.args.push(a)};
tn_Db.prototype.evaluate=function(a){var b=""+this.name.value;return(b=this.xpathfunctions[b])?b.call(this,a):new tn_n(tn_b)};
tn_Db.prototype.xpathfunctions={last:function(a){tn_f(this.args.length==0);return new tn_o(a.z())},position:function(a){tn_f(this.args.length==0);return new tn_o(a.position+1)},count:function(a){tn_f(this.args.length==1);a=this.args[0].evaluate(a);return new tn_o(a.c().length)},id:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a),c=[],d;if(b.type=="node-set"){d=[];var e=b.c();for(b=0;b<e.length;++b)for(var f=tn_h(e[b]).split(/\s+/),h=0;h<f.length;++h)d.push(f[h])}else d=b.a().split(/\s+/);
a=a.node.ownerDocument;for(b=0;b<d.length;++b)(e=a.getElementById(d[b]))&&c.push(e);return new tn_p(c)},"local-name":function(){tn_g("not implmented yet: XPath function local-name()")},"namespace-uri":function(){tn_g("not implmented yet: XPath function namespace-uri()")},name:function(a){tn_f(this.args.length==1||this.args.length==0);a=this.args.length==0?[a.node]:this.args[0].evaluate(a).c();return a.length==0?new tn_m(""):new tn_m(a[0].nodeName)},string:function(a){tn_f(this.args.length==1||this.args.length==
0);return this.args.length==0?new tn_m((new tn_p([a.node])).a()):new tn_m(this.args[0].evaluate(a).a())},concat:function(a){for(var b="",c=0;c<this.args.length;++c)b+=this.args[c].evaluate(a).a();return new tn_m(b)},document:function(a){var b=this.args[0].evaluate(a).a();if(b===""&&a.stylesheet)return new tn_p([a.stylesheet]);tn_g("Can't resolve uri in document(\""+b+'")')},"starts-with":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();return new tn_n(b.indexOf(a)==
0)},contains:function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();return new tn_n(b.indexOf(a)!=-1)},"substring-before":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();a=b.indexOf(a);b=a==-1?"":b.substr(0,a);return new tn_m(b)},"substring-after":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).a();a=this.args[1].evaluate(a).a();var c=b.indexOf(a);b=c==-1?"":b.substr(c+a.length);
return new tn_m(b)},substring:function(a){tn_f(this.args.length==2||this.args.length==3);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).b();if(this.args.length==2){c=Math.max(0,Math.round(c)-1);b=b.substr(c)}else{a=this.args[2].evaluate(a).b();var d=Math.round(c)-1;c=Math.max(0,d);a=Math.round(a)-Math.max(0,-d);b=b.substr(c,a)}return new tn_m(b)},"string-length":function(a){a=this.args.length>0?this.args[0].evaluate(a).a():(new tn_p([a.node])).a();return new tn_o(a.length)},"normalize-space":function(a){a=
this.args.length>0?this.args[0].evaluate(a).a():(new tn_p([a.node])).a();a=a.replace(/^\s*/,"").replace(/\s*$/,"").replace(/\s+/g," ");return new tn_m(a)},translate:function(a){tn_f(this.args.length==3);var b=this.args[0].evaluate(a).a(),c=this.args[1].evaluate(a).a();a=this.args[2].evaluate(a).a();for(var d=0;d<c.length;++d)b=b.replace(RegExp(c.charAt(d),"g"),a.charAt(d));return new tn_m(b)},"boolean":function(a){tn_f(this.args.length==1);return new tn_n(this.args[0].evaluate(a).d())},not:function(a){tn_f(this.args.length==
1);a=!this.args[0].evaluate(a).d();return new tn_n(a)},"true":function(){tn_f(this.args.length==0);return new tn_n(tn_)},"false":function(){tn_f(this.args.length==0);return new tn_n(tn_b)},lang:function(a){tn_f(this.args.length==1);var b=this.args[0].evaluate(a).a(),c;for(a=a.node;a&&a!=a.parentNode;){if(c=a.getAttribute("xml:lang"))break;a=a.parentNode}if(c){b=RegExp("^"+b+"$","i");return new tn_n(b.test(c)||b.test(c.replace(/_.*$/,"")))}else return new tn_n(tn_b)},number:function(a){tn_f(this.args.length==
1||this.args.length==0);return this.args.length==1?new tn_o(this.args[0].evaluate(a).b()):new tn_o((new tn_p([a.node])).b())},sum:function(a){tn_f(this.args.length==1);a=this.args[0].evaluate(a).c();for(var b=0,c=0;c<a.length;++c)b+=tn_h(a[c])-0;return new tn_o(b)},floor:function(a){tn_f(this.args.length==1);a=this.args[0].evaluate(a).b();return new tn_o(Math.floor(a))},ceiling:function(a){tn_f(this.args.length==1);a=this.args[0].evaluate(a).b();return new tn_o(Math.ceil(a))},round:function(a){tn_f(this.args.length==
1);a=this.args[0].evaluate(a).b();return new tn_o(Math.round(a))},"ext-join":function(a){tn_f(this.args.length==2);var b=this.args[0].evaluate(a).c();a=this.args[1].evaluate(a).a();for(var c="",d=0;d<b.length;++d){if(c)c+=a;c+=tn_h(b[d])}return new tn_m(c)},"ext-if":function(a){tn_f(this.args.length==3);return this.args[0].evaluate(a).d()?this.args[1].evaluate(a):this.args[2].evaluate(a)},"ext-cardinal":function(a){tn_f(this.args.length>=1);for(var b=this.args[0].evaluate(a).b(),c=[],d=0;d<b;++d)c.push(a.node);
return new tn_p(c)}};function tn_Eb(a,b){this.expr1=a;this.expr2=b}tn_Eb.prototype.evaluate=function(a){var b=this.expr1.evaluate(a).c();a=this.expr2.evaluate(a).c();for(var c=b.length,d=0;d<a.length;++d){for(var e=a[d],f=tn_b,h=0;h<c;++h)if(b[h]==e){f=tn_;h=c}f||b.push(e)}return new tn_p(b)};function tn_Fb(a,b){this.filter=a;this.rel=b}
tn_Fb.prototype.evaluate=function(a){for(var b=this.filter.evaluate(a).c(),c=[],d=0;d<b.length;++d)for(var e=this.rel.evaluate(a.clone(b[d],d,b)).c(),f=0;f<e.length;++f)c.push(e[f]);return new tn_p(c)};function tn_Gb(a,b){this.expr=a;this.predicate=b}tn_Gb.prototype.evaluate=function(a){for(var b=this.expr.evaluate(a).c(),c=0;c<this.predicate.length;++c){var d=b;b=[];for(var e=0;e<d.length;++e){var f=d[e];this.predicate[c].evaluate(a.clone(f,e,d)).d()&&b.push(f)}}return new tn_p(b)};
function tn_Hb(a){this.expr=a}tn_Hb.prototype.evaluate=function(a){return new tn_o(-this.expr.evaluate(a).b())};function tn_Ib(a,b,c){this.expr1=a;this.expr2=c;this.op=b}
tn_Ib.prototype.evaluate=function(a){var b;switch(this.op.value){case "or":b=new tn_n(this.expr1.evaluate(a).d()||this.expr2.evaluate(a).d());break;case "and":b=new tn_n(this.expr1.evaluate(a).d()&&this.expr2.evaluate(a).d());break;case "+":b=new tn_o(this.expr1.evaluate(a).b()+this.expr2.evaluate(a).b());break;case "-":b=new tn_o(this.expr1.evaluate(a).b()-this.expr2.evaluate(a).b());break;case "*":b=new tn_o(this.expr1.evaluate(a).b()*this.expr2.evaluate(a).b());break;case "mod":b=new tn_o(this.expr1.evaluate(a).b()%
this.expr2.evaluate(a).b());break;case "div":b=new tn_o(this.expr1.evaluate(a).b()/this.expr2.evaluate(a).b());break;case "=":b=this.compare(a,function(c,d){return c==d});break;case "!=":b=this.compare(a,function(c,d){return c!=d});break;case "<":b=this.compare(a,function(c,d){return c<d});break;case "<=":b=this.compare(a,function(c,d){return c<=d});break;case ">":b=this.compare(a,function(c,d){return c>d});break;case ">=":b=this.compare(a,function(c,d){return c>=d});break;default:tn_g("BinaryExpr.evaluate: "+
this.op.value)}return b};
tn_Ib.prototype.compare=function(a,b){var c=this.expr1.evaluate(a),d=this.expr2.evaluate(a);if(c.type=="node-set"&&d.type=="node-set"){c=c.c();var e=d.c();d=tn_b;for(var f=0;f<c.length;++f)for(var h=0;h<e.length;++h)if(b(tn_h(c[f]),tn_h(e[h]))){d=tn_;h=e.length;f=c.length}}else if(c.type=="node-set"||d.type=="node-set")if(c.type=="number"){c=c.b();e=d.c();d=tn_b;for(f=0;f<e.length;++f){h=tn_h(e[f])-0;if(b(c,h)){d=tn_;break}}}else if(d.type=="number"){e=c.c();c=d.b();d=tn_b;for(f=0;f<e.length;++f){h=
tn_h(e[f])-0;if(b(h,c)){d=tn_;break}}}else if(c.type=="string"){c=c.a();e=d.c();d=tn_b;for(f=0;f<e.length;++f){h=tn_h(e[f]);if(b(c,h)){d=tn_;break}}}else if(d.type=="string"){e=c.c();c=d.a();d=tn_b;for(f=0;f<e.length;++f){h=tn_h(e[f]);if(b(h,c)){d=tn_;break}}}else d=b(c.d(),d.d());else d=c.type=="boolean"||d.type=="boolean"?b(c.d(),d.d()):c.type=="number"||d.type=="number"?b(c.b(),d.b()):b(c.a(),d.a());return new tn_n(!!d)};function tn_Jb(a){this.value=a}tn_Jb.prototype.evaluate=function(){return new tn_m(this.value)};
function tn_Kb(a){this.value=a}tn_Kb.prototype.evaluate=function(){return new tn_o(this.value)};function tn_Lb(a){this.name=a}tn_Lb.prototype.evaluate=function(a){return a.J(this.name)};function tn_t(a){return a}function tn_Mb(a,b){b.absolute=tn_;return b}function tn_Nb(a,b){b.absolute=tn_;b.ca(tn_u(a.value));return b}function tn_Ob(){var a=new tn_q;a.j(tn_u("."));a.absolute=tn_;return a}function tn_Pb(a){var b=new tn_q;b.absolute=tn_;b.j(tn_u(a.value));return b}
function tn_Qb(a){var b=new tn_q;b.j(a);return b}function tn_Rb(a,b,c){a.j(c);return a}function tn_Sb(a,b){a.j(tn_u(b.value));return a}function tn_Tb(a,b,c){b=new tn_q;b.rootExpr=a;b.j(c);return b}function tn_Ub(a){return tn_u(a.value)}function tn_Vb(a){return tn_u(a.value)}function tn_Wb(a,b,c){return new tn_r(a.value,c)}function tn_Xb(a,b){return new tn_r("attribute",b)}function tn_Yb(a){return new tn_r("child",a)}function tn_Zb(a,b){a.la(b);return a}
function tn_u(a){switch(a){case "//":return new tn_r("descendant-or-self",new tn_vb);case ".":return new tn_r("self",new tn_vb);case "..":return new tn_r("parent",new tn_vb)}}function tn__b(){return new tn_wb}function tn_0b(a){return new tn_Ab(a.value)}function tn_1b(a){return new tn_Bb(a.value)}function tn_2b(a){a=a.value.replace(/\s*\($/,"");switch(a){case "node":return new tn_vb;case "text":return new tn_xb;case "comment":return new tn_yb;case "processing-instruction":return new tn_zb("")}}
function tn_3b(a,b){var c=a.replace(/\s*\($/,"");c!="processing-instruction"&&tn_g(c);return new tn_zb(b.value)}function tn_4b(a,b){return new tn_Cb(b)}function tn_5b(a,b){return b}function tn_6b(a){return new tn_Db(a)}function tn_7b(a,b,c,d){a=new tn_Db(a);a.T(c);for(c=0;c<d.length;++c)a.T(d[c]);return a}function tn_8b(a,b){return b}function tn_9b(a,b,c){return new tn_Eb(a,c)}function tn_$b(a,b,c){return new tn_Fb(a,c)}function tn_ac(a,b,c){c.ca(tn_u(b.value));return new tn_Fb(a,c)}
function tn_bc(a,b){return b.length>0?new tn_Gb(a,b):a}function tn_cc(a,b){return new tn_Hb(b)}function tn_v(a,b,c){return new tn_Ib(a,b,c)}function tn_dc(a){a=a.value.substring(1,a.value.length-1);return new tn_Jb(a)}function tn_ec(a){return new tn_Kb(a.value)}function tn_fc(a,b){return new tn_Lb(b.value)}
function tn_8a(a){if(a.charAt(0)=="$")return new tn_Lb(a.substr(1));else if(a.charAt(0)=="@"){a=new tn_Bb(a.substr(1));a=new tn_r("attribute",a);var b=new tn_q;b.j(a);return b}else if(a.match(/^[0-9]+$/))return new tn_Kb(a);else{a=new tn_Bb(a);a=new tn_r("child",a);b=new tn_q;b.j(a);return b}}function tn_9a(a){a=tn_Ca(a,"/");for(var b=new tn_q,c=0;c<a.length;++c){var d=new tn_Bb(a[c]);d=new tn_r("child",d);b.j(d)}return b}
var tn_s={ANCESTOR_OR_SELF:"ancestor-or-self",ANCESTOR:"ancestor",ATTRIBUTE:"attribute",CHILD:"child",DESCENDANT_OR_SELF:"descendant-or-self",DESCENDANT:"descendant",FOLLOWING_SIBLING:"following-sibling",FOLLOWING:"following",NAMESPACE:"namespace",PARENT:"parent",PRECEDING_SIBLING:"preceding-sibling",PRECEDING:"preceding",SELF:"self"},tn_gc=[tn_s.ANCESTOR_OR_SELF,tn_s.ANCESTOR,tn_s.ATTRIBUTE,tn_s.CHILD,tn_s.DESCENDANT_OR_SELF,tn_s.DESCENDANT,tn_s.FOLLOWING_SIBLING,tn_s.FOLLOWING,tn_s.NAMESPACE,tn_s.PARENT,
tn_s.PRECEDING_SIBLING,tn_s.PRECEDING,tn_s.SELF].join("|"),tn_hc={label:"|",prec:17,re:/^\|/},tn_fb={label:"//",prec:19,re:/^\/\//},tn_l={label:"/",prec:30,re:/^\//},tn_gb={label:"::",prec:20,re:/^::/},tn_ic={label:":",prec:1E3,re:/^:/},tn_jc={label:"[axis]",re:RegExp("^("+tn_gc+")")},tn_kc={label:"(",prec:34,re:/^\(/},tn_lc={label:")",re:/^\)/},tn_mc={label:"..",prec:34,re:/^\.\./},tn_nc={label:".",prec:34,re:/^\./},tn_eb={label:"@",prec:34,re:/^@/},tn_oc={label:",",re:/^,/},tn_db={label:"or",prec:10,
re:/^or\b/},tn_cb={label:"and",prec:11,re:/^and\b/},tn_pc={label:"=",prec:12,re:/^=/},tn_qc={label:"!=",prec:12,re:/^!=/},tn_rc={label:">=",prec:13,re:/^>=/},tn_sc={label:">",prec:13,re:/^>/},tn_tc={label:"<=",prec:13,re:/^<=/},tn_uc={label:"<",prec:13,re:/^</},tn_vc={label:"+",prec:14,re:/^\+/,left:tn_},tn_wc={label:"-",prec:14,re:/^\-/,left:tn_},tn_ab={label:"div",prec:15,re:/^div\b/,left:tn_},tn_bb={label:"mod",prec:15,re:/^mod\b/,left:tn_},tn_xc={label:"[",prec:32,re:/^\[/},tn_yc={label:"]",re:/^\]/},
tn_hb={label:"$",re:/^\$/},tn_zc={label:"[ncname]",re:RegExp("^"+tn_Ba)},tn_Ac={label:"*",prec:15,re:/^\*/,left:tn_},tn_Bc={label:"[litq]",prec:20,re:/^'[^\']*'/},tn_Cc={label:"[litqq]",prec:20,re:/^"[^\"]*"/},tn_Dc={label:"[number]",prec:35,re:/^\d+(\.\d*)?/},tn_ib={label:"[qname]",re:RegExp("^("+tn_Ba+":)?"+tn_Ba)},tn_Ec={label:"[nodetest-start]",re:/^(processing-instruction|comment|text|node)\(/},tn_$a=[tn_fb,tn_l,tn_mc,tn_nc,tn_gb,tn_ic,tn_jc,tn_Ec,tn_kc,tn_lc,tn_xc,tn_yc,tn_eb,tn_oc,tn_db,tn_cb,
tn_qc,tn_pc,tn_rc,tn_sc,tn_tc,tn_uc,tn_vc,tn_wc,tn_Ac,tn_hc,tn_bb,tn_ab,tn_Bc,tn_Cc,tn_Dc,tn_ib,tn_zc,tn_hb],tn_Fc={label:"LocationPath"},tn_w={label:"RelativeLocationPath"},tn_Gc={label:"AbsoluteLocationPath"},tn_x={label:"Step"},tn_y={label:"NodeTest"},tn_Hc={label:"Predicate"},tn_Ic={label:"Literal"},tn_z={label:"Expr"},tn_A={label:"PrimaryExpr"},tn_Jc={label:"Variablereference"},tn_Kc={label:"Number"},tn_Lc={label:"FunctionCall"},tn_Mc={label:"ArgumentRemainder"},tn_B={label:"PathExpr"},tn_Nc=
{label:"UnionExpr"},tn_Oc={label:"FilterExpr"},tn_Pc={label:"Digits"},tn_Qc=[tn_Fc,tn_w,tn_Gc,tn_x,tn_y,tn_Hc,tn_Ic,tn_z,tn_A,tn_Jc,tn_Kc,tn_Lc,tn_Mc,tn_B,tn_Nc,tn_Oc,tn_Pc],tn_qb={label:"?"},tn_pb={label:"*"},tn_rb={label:"+"},tn_Rc=[[tn_Fc,[tn_w],18,tn_t],[tn_Fc,[tn_Gc],18,tn_t],[tn_Gc,[tn_l,tn_w],18,tn_Mb],[tn_Gc,[tn_fb,tn_w],18,tn_Nb],[tn_Gc,[tn_l],0,tn_Ob],[tn_Gc,[tn_fb],0,tn_Pb],[tn_w,[tn_x],31,tn_Qb],[tn_w,[tn_w,tn_l,tn_x],31,tn_Rb],[tn_w,[tn_w,tn_fb,tn_x],31,tn_Sb],[tn_w,[tn_A,tn_l,tn_x],
31,tn_Tb],[tn_x,[tn_nc],33,tn_Ub],[tn_x,[tn_mc],33,tn_Vb],[tn_x,[tn_jc,tn_gb,tn_y],33,tn_Wb],[tn_x,[tn_eb,tn_y],33,tn_Xb],[tn_x,[tn_y],33,tn_Yb],[tn_x,[tn_x,tn_Hc],33,tn_Zb],[tn_y,[tn_Ac],33,tn__b],[tn_y,[tn_zc,tn_ic,tn_Ac],33,tn_0b],[tn_y,[tn_ib],33,tn_1b],[tn_y,[tn_Ec,tn_lc],33,tn_2b],[tn_y,[tn_Ec,tn_Ic,tn_lc],33,tn_3b],[tn_Hc,[tn_xc,tn_z,tn_yc],33,tn_4b],[tn_A,[tn_Jc],33,tn_t],[tn_A,[tn_kc,tn_z,tn_lc],33,tn_5b],[tn_A,[tn_Ic],30,tn_t],[tn_A,[tn_Kc],30,tn_t],[tn_A,[tn_Lc],30,tn_t],[tn_Lc,[tn_ib,
tn_kc,tn_lc],-1,tn_6b],[tn_Lc,[tn_ib,tn_kc,tn_z,tn_Mc,tn_pb,tn_lc],-1,tn_7b],[tn_Mc,[tn_oc,tn_z],-1,tn_8b],[tn_Nc,[tn_B],20,tn_t],[tn_Nc,[tn_Nc,tn_hc,tn_B],20,tn_9b],[tn_B,[tn_Fc],20,tn_t],[tn_B,[tn_Oc],19,tn_t],[tn_B,[tn_Oc,tn_l,tn_w],20,tn_$b],[tn_B,[tn_Oc,tn_fb,tn_w],20,tn_ac],[tn_Oc,[tn_A,tn_Hc,tn_pb],20,tn_bc],[tn_z,[tn_A],16,tn_t],[tn_z,[tn_Nc],16,tn_t],[tn_z,[tn_wc,tn_z],-1,tn_cc],[tn_z,[tn_z,tn_db,tn_z],-1,tn_v],[tn_z,[tn_z,tn_cb,tn_z],-1,tn_v],[tn_z,[tn_z,tn_pc,tn_z],-1,tn_v],[tn_z,[tn_z,
tn_qc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_uc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_tc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_sc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_rc,tn_z],-1,tn_v],[tn_z,[tn_z,tn_vc,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_wc,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_Ac,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_ab,tn_z],-1,tn_v,tn_],[tn_z,[tn_z,tn_bb,tn_z],-1,tn_v,tn_],[tn_Ic,[tn_Bc],-1,tn_dc],[tn_Ic,[tn_Cc],-1,tn_dc],[tn_Kc,[tn_Dc],-1,tn_ec],[tn_Jc,[tn_hb,tn_ib],200,tn_fc]],tn_mb=[];
function tn_6a(){function a(h,j,m){h[j]||(h[j]=[]);h[j].push(m)}if(!tn_mb.length){tn_Rc.sort(function(h,j){var m=h[1].length,l=j[1].length;return m<l?1:m>l?-1:0});for(var b=1,c=0;c<tn_Qc.length;++c)tn_Qc[c].key=b++;for(c=0;c<tn_$a.length;++c)tn_$a[c].key=b++;for(c=0;c<tn_Rc.length;++c){b=tn_Rc[c];for(var d=b[1],e=d.length-1;e>=0;--e)if(d[e]==tn_rb){a(tn_mb,d[e-1].key,b);break}else if(d[e]==tn_pb||d[e]==tn_qb){a(tn_mb,d[e-1].key,b);--e}else{a(tn_mb,d[e].key,b);break}}var f=0;tn_Ga(tn_mb,function(h){if(h)f+=
h.length})}}function tn_tb(a,b){for(var c=b.firstChild;c;c=c.nextSibling){a.push(c);arguments.callee(a,c)}}function tn_ub(a,b){for(var c=b.lastChild;c;c=c.previousSibling){a.push(c);arguments.callee(a,c)}}
function tn_5a(a,b){if(b.length!=0){for(var c=[],d=0;d<a.z();++d){var e=a.nodelist[d],f={node:e,key:[]};e=a.clone(e,0,[e]);for(var h=0;h<b.length;++h){var j=b[h],m=j.expr.evaluate(e),l;if(j.type=="text")l=m.a();else if(j.type=="number")l=m.b();f.key.push({value:l,order:j.order})}f.key.push({value:d,order:"ascending"});c.push(f)}c.sort(tn_Sc);f=[];for(d=0;d<c.length;++d)f.push(c[d].node);a.nodelist=f;a.Oa(0)}}
function tn_Sc(a,b){for(var c=0;c<a.key.length;++c){var d=a.key[c].order=="descending"?-1:1;if(a.key[c].value>b.key[c].value)return+1*d;else if(a.key[c].value<b.key[c].value)return-1*d}return 0}function tn_C(a,b){var c=tn_4a(a);return c=c.evaluate(b)};function tn_Tc(a,b){var c=(new tn_i).createDocumentFragment();tn_Uc(new tn_k(a,b),b,c);return c=tn_Ka(c)}
function tn_Uc(a,b,c){var d=c.nodeType==9?c:c.ownerDocument,e=b.nodeName.split(/:/);if(e.length==1||e[0]!="xsl")tn_Vc(a,b,c,d);else switch(e[1]){case "apply-imports":alert("not implemented: "+e[1]);break;case "apply-templates":e=(e=tn_D(b,"select"))?tn_C(e,a).c():a.node.childNodes;a=a.clone(e[0],0,e);tn_Wc(a,b);tn_Xc(a,b);var f=tn_D(b,"mode");d=b.ownerDocument.documentElement;e=[];for(b=0;b<d.childNodes.length;++b){var h=d.childNodes[b];h.nodeType==1&&h.nodeName=="xsl:template"&&h.getAttribute("mode")==
f&&e.push(h)}for(d=0;d<a.z();++d){h=a.nodelist[d];for(b=0;b<e.length;++b)tn_Uc(a.clone(h,d),e[b],c)}break;case "attribute":e=tn_D(b,"name");e=tn_Yc(e,a);h=d.createDocumentFragment();tn_E(a,b,h);b=tn_h(h);c.setAttribute(e,b);break;case "attribute-set":alert("not implemented: "+e[1]);break;case "call-template":e=tn_D(b,"name");d=b.ownerDocument.documentElement;a=a.clone();tn_Wc(a,b);for(b=0;b<d.childNodes.length;++b){h=d.childNodes[b];if(h.nodeType==1&&h.nodeName=="xsl:template"&&h.getAttribute("name")==
e){tn_E(a,h,c);break}}break;case "choose":tn_Zc(a,b,c);break;case "comment":h=d.createDocumentFragment();tn_E(a,b,h);b=tn_h(h);b=d.createComment(b);c.appendChild(b);break;case "copy":(h=tn__c(c,a.node,d))&&tn_E(a,b,h);break;case "copy-of":e=tn_D(b,"select");b=tn_C(e,a);if(b.type=="node-set"){e=b.c();for(b=0;b<e.length;++b)tn_0c(c,e[b],d)}else{h=tn_Qa(d,b.a());c.appendChild(h)}break;case "decimal-format":alert("not implemented: "+e[1]);break;case "element":e=tn_D(b,"name");e=tn_Yc(e,a);h=d.createElement(e);
c.appendChild(h);tn_E(a,b,h);break;case "fallback":alert("not implemented: "+e[1]);break;case "for-each":tn_1c(a,b,c);break;case "if":d=tn_D(b,"test");d=tn_C(d,a);d!=tn_a&&d.d()&&tn_E(a,b,c);break;case "import":alert("not implemented: "+e[1]);break;case "include":alert("not implemented: "+e[1]);break;case "key":alert("not implemented: "+e[1]);break;case "message":alert("not implemented: "+e[1]);break;case "namespace-alias":alert("not implemented: "+e[1]);break;case "number":alert("not implemented: "+
e[1]);break;case "otherwise":alert("error if here: "+e[1]);break;case "output":break;case "preserve-space":break;case "processing-instruction":alert("not implemented: "+e[1]);break;case "sort":break;case "strip-space":alert("not implemented: "+e[1]);break;case "stylesheet":case "transform":tn_E(a,b,c);break;case "template":(d=tn_D(b,"match"))&&tn_2c(d,a)&&tn_E(a,b,c);break;case "text":b=tn_h(b);h=d.createTextNode(b);c.appendChild(h);break;case "value-of":e=tn_D(b,"select");b=tn_C(e,a).a();h=d.createTextNode(b);
c.appendChild(h);break;case "param":tn_3c(a,b,tn_b);break;case "variable":tn_3c(a,b,tn_);break;case "when":alert("error if here: "+e[1]);break;case "with-param":alert("error if here: "+e[1]);break;default:alert("error if here: "+e[1])}}function tn_Wc(a,b){for(var c=0;c<b.childNodes.length;++c){var d=b.childNodes[c];d.nodeType==1&&d.nodeName=="xsl:with-param"&&tn_3c(a,d,tn_)}}
function tn_Xc(a,b){for(var c=[],d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(e.nodeType==1&&e.nodeName=="xsl:sort"){var f=tn_D(e,"select");f=tn_4a(f);var h=tn_D(e,"data-type")||"text";e=tn_D(e,"order")||"ascending";c.push({expr:f,type:h,order:e})}}tn_5a(a,c)}function tn_3c(a,b,c){var d=tn_D(b,"name"),e=tn_D(b,"select");if(b.childNodes.length>0){e=b.ownerDocument.createDocumentFragment();tn_E(a,b,e);b=new tn_p([e])}else b=e?tn_C(e,a):new tn_m("");if(c||!a.J(d))a.fa(d,b)}
function tn_Zc(a,b,c){for(var d=0;d<b.childNodes.length;++d){var e=b.childNodes[d];if(e.nodeType==1)if(e.nodeName=="xsl:when"){var f=tn_D(e,"test");if(tn_C(f,a).d()){tn_E(a,e,c);break}}else if(e.nodeName=="xsl:otherwise"){tn_E(a,e,c);break}}}function tn_1c(a,b,c){var d=tn_D(b,"select");d=tn_C(d,a).c();a=a.clone(d[0],0,d);tn_Xc(a,b);for(d=0;d<a.z();++d){var e=a.nodelist[d];tn_E(a.clone(e,d),b,c)}}function tn_E(a,b,c){a=a.clone();for(var d=0;d<b.childNodes.length;++d)tn_Uc(a,b.childNodes[d],c)}
function tn_Vc(a,b,c,d){if(b.nodeType==3){if(tn_4c(b)){d=d.createTextNode(b.nodeValue);c.appendChild(d)}}else if(b.nodeType==1){d=d.createElement(b.nodeName);for(var e=0;e<b.attributes.length;++e){var f=b.attributes[e];if(f){var h=f.nodeName;f=tn_Yc(f.nodeValue,a);d.setAttribute(h,f)}}c.appendChild(d);tn_E(a,b,d)}else tn_E(a,b,c)}
function tn_4c(a){if(!a.nodeValue.match(/^\s*$/))return tn_;a=a.parentNode;if(a.nodeName=="xsl:text")return tn_;for(;a&&a.nodeType==1;){var b=a.getAttribute("xml:space");if(b)if(b=="default")break;else if(b=="preserve")return tn_;a=a.parentNode}return tn_b}function tn_Yc(a,b){var c=tn_Ca(a,"{");if(c.length==1)return a;for(var d="",e=0;e<c.length;++e){var f=tn_Ca(c[e],"}");if(f.length!=2)d+=c[e];else{var h=tn_C(f[0],b).a();d+=h+f[1]}}return d}
function tn_D(a,b){var c=a.getAttribute(b);return c?tn_Ra(c):c}function tn_0c(a,b,c){if(b.nodeType==11||b.nodeType==9)for(var d=0;d<b.childNodes.length;++d)arguments.callee(a,b.childNodes[d],c);else{var e=tn__c(a,b,c);if(e){for(d=0;d<b.attributes.length;++d)arguments.callee(e,b.attributes[d],c);for(d=0;d<b.childNodes.length;++d)arguments.callee(e,b.childNodes[d],c)}}}
function tn__c(a,b,c){if(b.nodeType==1){b=c.createElement(b.nodeName);a.appendChild(b);return b}if(b.nodeType==3){b=c.createTextNode(b.nodeValue);a.appendChild(b)}else if(b.nodeType==4){b=c.createCDATASection(b.nodeValue);a.appendChild(b)}else if(b.nodeType==8){b=c.createComment(b.nodeValue);a.appendChild(b)}else b.nodeType==2&&a.setAttribute(b.nodeName,b.nodeValue);return tn_a}
function tn_2c(a,b){var c=tn_4a(a),d;if(c.steps&&!c.absolute&&c.steps.length==1&&c.steps[0].axis=="child"&&c.steps[0].predicate.length==0)d=c.steps[0].nodetest.evaluate(b).d();else{d=tn_b;for(var e=b.node;!d&&e;){for(var f=c.evaluate(b.clone(e,0,[e])).c(),h=0;h<f.length;++h)if(f[h]==b.node){d=tn_;break}e=e.parentNode}}return d};function tn_5c(a,b){window[a]=b}tn_5c("nxslProcess",tn_Ya);tn_5c("xmlParse",tn_Wa);tn_5c("xsltProcess",tn_Tc);tn_5c("xmlText",tn_Ka);tn_5c("xmlImportNode",tn_Da);var tn_6c="http://www.google.com/images/infowindow/";function tn_7c(){return tn_6c+"transparent.png"}var tn_8c=Number.MAX_VALUE;var tn_9c="windo";function tn_F(a,b,c,d,e,f){var h=((b?b.ownerDocument:tn_a)||document).createElement(a);c&&tn_G(h,c);d&&tn_$c(h,d);h.style.display="none";if(b&&!e){tn_H(b,h);if(b[tn_9c])h[tn_9c]=b[tn_9c]}f||window.setTimeout(function(){h.style.display=""},0);return h}function tn_ad(a,b){var c=((b?b.ownerDocument:tn_a)||document).createTextNode(a);b&&tn_H(b,c);return c}function tn_I(a){return tn_J(a)+"px"}function tn_G(a,b){var c=a.style;c.position="absolute";c.left=tn_I(b.x);c.top=tn_I(b.y)}
function tn_$c(a,b){var c=a.style;c.width=tn_I(b.width);c.height=tn_I(b.height)}function tn_K(a,b){a.style.width=tn_I(b)}function tn_L(a,b){a.style.height=tn_I(b)}function tn_M(a){a.style.display="none"}function tn_N(a){a.style.display=""}function tn_bd(a){a.style.visibility="hidden"}function tn_cd(a){a.style.visibility=""}function tn_dd(a){tn_ed(a,"hidden")}function tn_ed(a,b){a.style.overflow=b}var tn_O=Math.min,tn_P=Math.max,tn_J=Math.round;
function tn_Q(a,b){try{a.style.cursor=b}catch(c){b=="pointer"&&tn_Q(a,"hand")}}function tn_fd(a){tn_gd(a,"gmnoscreen");tn_hd(a,"gmnoprint")}function tn_id(a,b,c){return window.setTimeout(function(){b.apply(a)},c)}function tn_jd(a){a=a.target||a.srcElement;if(a.nodeType==3)a=a.parentNode;return a}function tn_H(a,b){a.appendChild(b)}function tn_R(a){if(a.parentNode){a.parentNode.removeChild(a);tn_kd(a)}}function tn_ld(a){for(var b;b=a.firstChild;){tn_kd(b);a.removeChild(b)}}
function tn_md(a,b){if(a.innerHTML!=b){tn_ld(a);a.innerHTML=b}}function tn_nd(a){if(tn_S.k())a.style.MozUserSelect="none";else{a.unselectable="on";a.onselectstart=tn_od}}function tn_pd(a,b){for(var c=a.length,d=0;d<c;++d)b(a[d],d)}function tn_qd(a,b,c){for(var d in a)if(c||!a.hasOwnProperty||a.hasOwnProperty(d))b(d,a[d])}function tn_rd(a,b,c,d){c=c||0;d=d||b.length;for(c=c;c<d;++c)a.push(b[c])}function tn_od(){return tn_b}
function tn_sd(a,b){if(tn_S.type==1)a.style.filter="alpha(opacity="+tn_J(b*100)+")";else a.style.opacity=b}function tn_td(a,b,c){a=tn_F("div",a,b,c);a.style.backgroundColor="black";tn_sd(a,0.35);return a}function tn_T(a,b){var c=(a?a.ownerDocument:tn_a)||document;if(a.currentStyle){c=tn_ud(b);return a.currentStyle[c]}else if(c.defaultView&&c.defaultView.getComputedStyle)return(c=c.defaultView.getComputedStyle(a,""))?c.getPropertyValue(b):"";else{c=tn_ud(b);return a.style[c]}}var tn_vd="__mapsBaseCssDummy__";
function tn_wd(a,b,c){b=c?c:tn_T(a,b);if(typeof b=="number")return b;else if(isNaN(parseInt(b,10)))return b;else if(b.length>2&&b.substring(b.length-2)=="px")return parseInt(b,10);else{if(c=a.ownerDocument.getElementById(tn_vd))a.parentNode.appendChild(c);else{c=tn_F("div",a,new tn_c(0,0),new tn_U(0,0));c.id=tn_vd;tn_bd(c)}c.style.width="0px";c.style.width=b;return c.offsetWidth}}var tn_xd="border-left-width",tn_yd="border-top-width";
function tn_zd(a){return new tn_U(tn_Ad(a,tn_xd),tn_Ad(a,tn_yd))}function tn_Ad(a,b){var c=tn_T(a,b);if(isNaN(parseInt(c,10)))return 0;return tn_wd(a,b,c)}function tn_ud(a){return a.replace(/-(\w)/g,function(b,c){return(""+c).toUpperCase()})}function tn_Bd(a){a.length=0}function tn_Cd(a){var b=tn_b;if(a&&typeof a=="object")b=typeof Window=="function"?a instanceof Window:typeof a.navigator=="object"&&typeof a.history=="object"&&typeof a.document=="object";return b}
function tn_Dd(a){return a=tn_Cd(a)?a:a&&a[tn_9c]?a[tn_9c]:window}function tn_Ed(a,b){var c=tn_Dd(b);return a[tn_9c]=c};function tn_Fd(a,b,c){tn_Gd([a],function(d){b(d[0])},c)}
function tn_Gd(a,b,c){c=c||screen.width;var d=tn_F("div",window.document.body,new tn_c(-screen.width,-screen.height),new tn_U(c,screen.height)),e=[];for(c=0;c<a.length;c++){var f=tn_F("div",d,tn_c.ORIGIN);tn_H(f,a[c]);e.push(f)}window.setTimeout(function(){for(var h=[],j=new tn_U(0,0),m=0;m<e.length;m++){var l=e[m],g=new tn_U(l.offsetWidth,l.offsetHeight);h.push(g);l.removeChild(a[m]);tn_R(l);j.width=tn_P(j.width,g.width);j.height=tn_P(j.height,g.height)}tn_R(d);e=tn_a;b(h,j)},0)};function tn_Hd(a,b,c,d,e,f,h){if(e&&tn_S.type==1){b=tn_F("div",b,c,d);b.style.overflow="hidden";if(d&&f)b.sizingMethod="scale";d=tn_F("img",b);tn_bd(d);tn_Id(d,tn_Jd,tn_Kd)}else{b=tn_F("img",b,c,d);h&&tn_Id(b,tn_Jd,tn_Ld)}if(h)b.hideAndTrackLoading=tn_;tn_nd(b);if(tn_S.type==1)b.galleryImg="no";b.style.border=tn_I(0);b.style.padding=tn_I(0);b.style.margin=tn_I(0);b.oncontextmenu=tn_Md;tn_Nd(b,a);return b}
function tn_Kd(){var a=this.parentNode;a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod="+(a.sizingMethod?a.sizingMethod:"crop")+',src="'+this.src+'")';if(a.hideAndTrackLoading)a.loaded=tn_}function tn_Nd(a,b){if(a.tagName=="DIV"){a.firstChild.src=b;a.src=b;if(a.hideAndTrackLoading){a.style.filter="";a.loaded=tn_b}}else if(a.hideAndTrackLoading&&b!=tn_7c()){if(b!=tn_7c()){a.loaded=tn_b;a.pendingSrc=b}else a.pendingSrc=tn_a;a.src=tn_7c()}else a.src=b}
function tn_Ld(){var a=this;if(a.src==tn_7c()&&a.pendingSrc){a.src=a.pendingSrc;a.pendingSrc=tn_a}else a.loaded=tn_};var tn_Od="click",tn_Pd="contextmenu",tn_Qd="dblclick",tn_Jd="load",tn_Rd="mousedown",tn_Sd="mousewheel",tn_Td="DOMMouseScroll",tn_Ud="unload",tn_Vd="closeclick",tn_Wd="maximizeclick",tn_Xd="restoreclick",tn_Yd="maximizeend",tn_Zd="restoreend",tn__d="clearlisteners",tn_0d="logclick";var tn_1d=tn_b;function tn_V(){this.n=[]}function tn_2d(){}tn_V.instance=function(a){a||(a=window);if(!a.gEventListenerPool)a.gEventListenerPool=new tn_V;return a.gEventListenerPool};tn_V.remove=function(a){tn_V.instance(tn_Dd(a)).Ia(a)};tn_V.prototype.Ia=function(a){var b=this.n.pop(),c=a.qa();if(c<this.n.length){this.n[c]=b;b.D(c)}a.D(-1)};tn_V.push=function(a){tn_V.instance(tn_Dd(a)).Ha(a)};tn_V.prototype.Ha=function(a){this.n.push(a);a.D(this.n.length-1)};
tn_V.prototype.clear=function(){for(var a=0;a<this.n.length;++a)this.n[a].D(-1);this.n=[]};function tn_3d(a,b,c){a=new tn_W(a,b,c,0);tn_V.push(a);return a}function tn_4d(a){a.remove();tn_V.remove(a)}function tn_5d(a){tn_X(a,tn__d);tn_pd(tn_6d(a),function(b){b.remove();tn_V.remove(b)})}function tn_6d(a,b){var c=[],d=a.__e_;if(d)if(b)d[b]&&tn_rd(c,d[b]);else tn_qd(d,function(e,f){tn_rd(c,f)});return c}
function tn_7d(a,b,c){var d=tn_a,e=a.__e_;if(e){d=e[b];if(!d){d=[];if(c)e[b]=d}}else{d=[];if(c){a.__e_={};a.__e_[b]=d}}return d}function tn_X(a,b){var c=[];tn_rd(c,arguments,2);tn_pd(tn_6d(a,b),function(d){if(tn_1d)d.apply(a,c);else try{d.apply(a,c)}catch(e){}})}
function tn_Id(a,b,c){if(tn_S.type==2&&b==tn_Qd){a["on"+b]=c;c=new tn_W(a,b,c,3)}else if(a.addEventListener){a.addEventListener(b,c,tn_b);c=new tn_W(a,b,c,1)}else if(a.attachEvent){c=tn_8d(a,c);a.attachEvent("on"+b,c);c=new tn_W(a,b,c,2)}else{a["on"+b]=c;c=new tn_W(a,b,c,3)}var d=tn_Dd(a);if(a!=d||b!=tn_Ud)tn_V.push(c);return c}function tn_Y(a,b,c,d){c=tn_9d(c,d);return tn_Id(a,b,c)}function tn_$d(a,b,c){tn_Y(a,tn_Od,b,c);tn_S.type==1&&tn_Y(a,tn_Qd,b,c)}
function tn_9d(a,b){return function(c){if(!c)c=window.event;if(c&&!c.target)c.target=c.srcElement;b.call(a,c,this)}}function tn_8d(a,b){return function(){return b.apply(a,arguments)}}function tn_W(a,b,c,d){tn_f(a);tn_f(typeof c=="function");var e=this;e.r=a;e.I=b;e.L=c;e.Ya=d;e.wa=-1;tn_Ed(e,a);tn_7d(a,b,tn_).push(e)}
tn_W.prototype.remove=function(){var a=this;switch(a.Ya){case 1:a.r.removeEventListener(a.I,a.L,tn_b);break;case 2:a.r.detachEvent("on"+a.I,a.L);break;case 3:a.r["on"+a.I]=tn_a}tn_Fa(tn_7d(a.r,a.I),a);a.r=tn_a;a.L=tn_a;a.remove=tn_2d;a.apply=tn_2d};tn_W.prototype.qa=function(){return this.wa};tn_W.prototype.D=function(a){this.wa=a};tn_W.prototype.apply=function(a,b){return this.L.apply(a,b)};function tn_kd(a){tn_Xa(a,tn_5d)}
function tn_ae(a){a.type==tn_Od&&tn_X(document,tn_0d,a);if(tn_S.type==1){window.event.cancelBubble=tn_;window.event.returnValue=tn_b}else{a.preventDefault();a.stopPropagation()}}function tn_be(a){a.type==tn_Od&&tn_X(document,tn_0d,a);if(tn_S.type==1)window.event.cancelBubble=tn_;else a.stopPropagation()}function tn_Md(a){if(tn_S.type==1)window.event.returnValue=tn_b;else a.preventDefault()};var tn_S,tn_ce=["opera","msie","safari","firefox","mozilla"],tn_de=["x11;","macintosh","windows"];
function tn_ee(a){this.os=this.type=-1;this.revision=this.version=0;a=a.toLowerCase();for(var b=0;b<tn_ce.length;b++){var c=tn_ce[b];if(a.indexOf(c)!=-1){this.type=b;b=RegExp(c+"[ /]?([0-9]+(.[0-9]+)?)");if(b.exec(a)!=tn_a)this.version=parseFloat(RegExp.$1);break}}for(b=0;b<tn_de.length;b++){c=tn_de[b];if(a.indexOf(c)!=-1){this.os=b;break}}if(this.type==4||this.type==3)if(/\brv:\s*(\d+\.\d+)/.exec(a))this.revision=parseFloat(RegExp.$1)}
tn_ee.prototype.k=function(){return this.type==3||this.type==4};tn_S=new tn_ee(navigator.userAgent);tn_c.ORIGIN=new tn_c(0,0);tn_c.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function tn_U(a,b){this.width=a;this.height=b}tn_U.ZERO=new tn_U(0,0);tn_U.prototype.toString=function(){return"("+this.width+", "+this.height+")"};function tn_fe(a){this.minX=this.minY=tn_8c;this.maxX=this.maxY=-tn_8c;var b=arguments;if(a&&a.length)for(b=0;b<a.length;b++)this.extend(a[b]);else if(b.length>=4){this.minX=b[0];this.minY=b[1];this.maxX=b[2];this.maxY=b[3]}}
tn_fe.prototype.min=function(){return new tn_c(this.minX,this.minY)};tn_fe.prototype.max=function(){return new tn_c(this.maxX,this.maxY)};tn_fe.prototype.toString=function(){return"("+this.min()+", "+this.max()+")"};tn_fe.prototype.extend=function(a){var b=this;b.minX=tn_O(b.minX,a.x);b.maxX=tn_P(b.maxX,a.x);b.minY=tn_O(b.minY,a.y);b.maxY=tn_P(b.maxY,a.y)};
tn_fe.intersection=function(a,b){return new tn_fe([new tn_c(tn_P(a.minX,b.minX),tn_P(a.minY,b.minY)),new tn_c(tn_O(a.maxX,b.maxX),tn_O(a.maxY,b.maxY))])};function tn_hd(a,b){var c=a.className?""+a.className:"";if(c){c=c.split(/\s+/);for(var d=tn_b,e=0;e<c.length;++e)if(c[e]==b){d=tn_;break}d||c.push(b);a.className=c.join(" ")}else a.className=b}function tn_gd(a,b){var c=a.className?""+a.className:"";if(!(!c||c.indexOf(b)==-1)){c=c.split(/\s+/);for(var d=0;d<c.length;++d)c[d]==b&&c.splice(d--,1);a.className=c.join(" ")}};function tn_ge(){}tn_ge.monitor=function(){};tn_ge.monitorAll=function(){};tn_ge.dump=function(){};function tn_Z(){var a=tn_F("div",document.body),b=a.style;b.position="absolute";b.left=tn_I(7);b.bottom=tn_I(4);b.zIndex=1E4;var c=tn_td(a,new tn_c(2,2)),d=tn_F("div",a);b=d.style;b.position="relative";b.zIndex=1;b.fontFamily="Verdana,Arial,sans-serif";b.fontSize="small";b.border="1px solid black";var e=[["Clear",this.clear],["Close",this.close]],f=tn_F("div",d);b=f.style;b.position="relative";b.zIndex=2;b.backgroundColor="#979797";b.color="white";b.fontSize="85%";b.padding=tn_I(2);tn_Q(f,"default");
tn_nd(f);tn_ad("Log",f);for(b=0;b<e.length;b++){var h=e[b];tn_ad(" - ",f);var j=tn_F("span",f);j.style.textDecoration="underline";tn_ad(h[0],j);tn_$d(j,this,h[1]);tn_Q(j,"pointer")}d=tn_F("div",d);b=d.style;b.backgroundColor="white";b.width="80em";b.height="10em";b.overflow=tn_S.k()?"-moz-scrollbars-vertical":"auto";tn_Id(d,tn_Rd,tn_be);this.N=d;this.U=a;this.i=c}tn_Z.instance=function(){var a=tn_Z.r;if(!a){a=new tn_Z;tn_Z.r=a}return a};
tn_Z.prototype.write=function(a,b){var c=this.oa();if(b){c=tn_F("span",c);c.style.color=b}tn_ad(a,c);this.Ja()};tn_Z.prototype.clear=function(){this.N.innerHTML=""};tn_Z.prototype.close=function(){tn_R(this.U)};tn_Z.prototype.oa=function(){var a=tn_F("div",this.N),b=a.style;b.fontSize="85%";b.borderBottom="1px solid silver";b.paddingBottom=tn_I(2);b=tn_F("div",a);b.style.color="gray";b.style.fontSize="75%";tn_ad(this.Sa(),b);return a};
tn_Z.prototype.Ja=function(){this.N.scrollTop=this.N.scrollHeight;this.Qa()};tn_Z.prototype.Sa=function(){var a=new Date;return this.B(a.getHours(),2)+":"+this.B(a.getMinutes(),2)+":"+this.B(a.getSeconds(),2)+":"+this.B(a.getMilliseconds(),3)};tn_Z.prototype.B=function(a,b){for(var c=a.toString();c.length<b;)c="0"+c;return c};tn_Z.prototype.Qa=function(){tn_$c(this.i,new tn_U(this.U.offsetWidth,this.U.offsetHeight))};var tn_he="overflow",tn_ie="position",tn_je="visible",tn_ke="static",tn_le="BODY";
function tn_me(a,b){for(var c=new tn_c(0,0);a&&a!=b;){a.nodeName==tn_le&&tn_ne(c,a);var d=tn_zd(a);c.x+=d.width;c.y+=d.height;if(a.nodeName!=tn_le||!tn_S.k()){c.x+=a.offsetLeft;c.y+=a.offsetTop}if(tn_S.k()&&tn_S.revision>=1.8&&a.offsetParent&&a.offsetParent.nodeName!=tn_le&&tn_T(a.offsetParent,tn_he)!=tn_je){d=tn_zd(a.offsetParent);c.x+=d.width;c.y+=d.height}if(a.offsetParent){c.x-=a.offsetParent.scrollLeft;c.y-=a.offsetParent.scrollTop}if(tn_S.type!=1&&tn_oe(a)){if(tn_S.k()){c.x-=self.pageXOffset;
c.y-=self.pageYOffset;d=tn_zd(a.offsetParent.parentNode);c.x+=d.width;c.y+=d.height}break}if(tn_S.type==2&&a.offsetParent){d=tn_zd(a.offsetParent);c.x-=d.width;c.y-=d.height}a=a.offsetParent}if(tn_S.type==1&&!b&&document.documentElement){c.x+=document.documentElement.clientLeft;c.y+=document.documentElement.clientTop}if(b&&a==tn_a){d=tn_me(b);return new tn_c(c.x-d.x,c.y-d.y)}else return c}
function tn_oe(a){if(a.offsetParent&&a.offsetParent.nodeName==tn_le&&tn_T(a.offsetParent,tn_ie)==tn_ke)if(tn_S.type==0&&tn_T(a,tn_ie)!=tn_ke)return tn_;else if(tn_S.type!=0&&tn_T(a,tn_ie)=="absolute")return tn_;return tn_b}
function tn_ne(a,b){var c=tn_b;if(tn_S.k()){c=tn_T(b,tn_he)!=tn_je&&tn_T(b.parentNode,tn_he)!=tn_je;var d=tn_T(b,tn_ie)!=tn_ke;if(d||c){a.x+=tn_wd(b,"margin-left");a.y+=tn_wd(b,"margin-top");var e=tn_zd(b.parentNode);a.x+=e.width;a.y+=e.height}if(d){a.x+=tn_wd(b,"left");a.y+=tn_wd(b,"top")}}if((tn_S.k()||tn_S.type==1)&&document.compatMode!="BackCompat"||c)if(self.pageYOffset){a.x-=self.pageXOffset;a.y-=self.pageYOffset}else{a.x-=document.documentElement.scrollLeft;a.y-=document.documentElement.scrollTop}}
function tn_pe(a,b){if(typeof a.offsetX!="undefined"){var c=tn_jd(a),d=tn_me(c,b),e=new tn_c(a.offsetX,a.offsetY);if(tn_S.type==2){c=tn_zd(c);e.x-=c.width;e.y-=c.height}return new tn_c(d.x+e.x,d.y+e.y)}else if(typeof a.clientX!="undefined"){d=tn_S.type==2?new tn_c(a.pageX-self.pageXOffset,a.pageY-self.pageYOffset):new tn_c(a.clientX,a.clientY);e=tn_me(b);return new tn_c(d.x-e.x,d.y-e.y)}else return tn_c.ORIGIN};function tn_qe(a){this.ticks=a;this.tick=0}tn_qe.prototype.reset=function(){this.tick=0};tn_qe.prototype.next=function(){this.tick++;var a=Math.PI*(this.tick/this.ticks-0.5);return(Math.sin(a)+1)/2};tn_qe.prototype.more=function(){return this.tick<this.ticks};tn_qe.prototype.extend=function(){if(this.tick>this.ticks/3)this.tick=tn_J(this.ticks/3)};var tn_re=tn_b;function tn_se(a,b,c){this.name=a;if(typeof b=="string"){a=tn_F("div",tn_a);tn_md(a,b);b=a}this.contentElem=b;b.style.zIndex=9500;this.onclick=c}function tn__(){this.da=new tn_d(0,0,0,0);this.ba=tn_U.ZERO;this.f=[];this.l=[];this.Q=[];this.ha=[];this.s=this.v=0;this.q=this.H(tn_U.ZERO);this.g={};this.m=this.S=this.Aa=tn_b;this.ga=new tn_c(8,8);this.aa="ltr"}
tn__.prototype.create=function(a,b){var c=this.g,d=tn_te(c,a,[["iw_n",628,6,0,0,"iw_n1"],["iw_n",628,6,0,0,"iw_n2"],["iw_w",6,598,0,0],["iw_e",6,598,0,0],["iw_s0",628,6,0,0,"iw_s1"],["iw_s0",628,6,0,0,"iw_s2"],["iw_c",628,598,0,0]]),e=new tn_U(6,6);tn_0(c,d,"iw_nw",e);tn_0(c,d,"iw_ne",e);tn_0(c,d,"iw_xtap",new tn_U(32,21));tn_0(c,d,"iw_xtap_l",new tn_U(32,21));tn_0(c,d,"iw_xtap_u",new tn_U(32,21));tn_0(c,d,"iw_xtap_ul",new tn_U(32,21));tn_0(c,d,"iw_xtap_rd",new tn_U(21,32));tn_0(c,d,"iw_xtap_ld",
new tn_U(21,32));tn_0(c,d,"iw_sw0",e,"iw_sw");tn_0(c,d,"iw_se0",e,"iw_se");tn_fd(d);this.e=d;e=new tn_U(8,8);var f=tn_te(c,b,[["iws_n",628,8,0,0,"iws_n1"],["iws_n",628,8,0,0,"iws_n2"],["iws_w",8,598,0,0],["iws_e",8,598,0,0],["iws_s",628,8,0,0,"iws_s1"],["iws_s",628,8,0,0,"iws_s2"],["iws_c",628,598,0,0]]);tn_0(c,f,"iws_nw",e);tn_0(c,f,"iws_ne",e);tn_0(c,f,"iws_sw",e);tn_0(c,f,"iws_se",e);tn_0(c,f,"iws_tap",new tn_U(37,16));tn_0(c,f,"iws_tap_l",new tn_U(32,16));tn_0(c,f,"iws_tap_u",new tn_U(37,26));
tn_0(c,f,"iws_tap_ul",new tn_U(32,26));tn_0(c,f,"iws_tap_rd",new tn_U(16,37));tn_0(c,f,"iws_tap_ld",new tn_U(26,37));tn_0(c,f,"iws_tab_dl",new tn_U(8,28));tn_0(c,f,"iws_tab_dr",new tn_U(14,28));tn_0(c,f,"iws_tab_l",new tn_U(8,28));tn_0(c,f,"iws_tab_r",new tn_U(14,28));tn_M(c.iws_tab_dl);tn_M(c.iws_tab_dr);tn_M(c.iws_tab_l);tn_M(c.iws_tab_r);tn_fd(f);this.i=f;e=new tn_U(14,13);f=tn_0(c,d,"close",e,"close",tn_);f.style.zIndex=1E4;tn_Q(f,"pointer");tn_$d(f,this,this.Fa);f=tn_0(c,d,"maximize",e,"maximize",
tn_);f.style.zIndex=1E4;tn_bd(f);tn_Q(f,"pointer");tn_$d(f,this,this.maximize);c=tn_0(c,d,"restore",e,"restore",tn_);c.style.zIndex=10001;tn_bd(c);tn_Q(c,"pointer");tn_$d(c,this,this.restore);tn_Y(d,tn_Rd,this,this.X);tn_Y(d,tn_Qd,this,this.pa);tn_Y(d,tn_Od,this,this.X);tn_Y(d,tn_Pd,this,tn_be);tn_Y(d,tn_Sd,this,tn_be);tn_Y(d,tn_Td,this,tn_be);this.Pa();this.hide()};tn__.prototype.remove=function(){tn_R(this.i);tn_R(this.e)};
tn__.prototype.ka=function(a){if(a){tn_N(this.g.maximize);tn_N(this.g.restore)}else{tn_M(this.g.maximize);tn_M(this.g.restore)}};tn__.prototype.G=function(a){this.g.close.style.visibility=a?"visible":"hidden"};tn__.prototype.La=function(a){this.aa=a===tn_||a==="rtl"?"rtl":"ltr"};tn__.prototype.za=function(a){this.Aa=a};tn__.prototype.Ba=function(a){this.Ca=a};tn__.prototype.ja=function(a){this.S=a};
tn__.prototype.F=function(a){if(!a.getClientRects)return this.p(tn_ga(a));var b=this.A(),c=this.g,d=b.width,e=b.height,f=window.innerWidth||document.body.scrollWidth;b=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft;var h=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_M(c.iw_xtap);tn_M(c.iw_xtap_l);tn_M(c.iw_xtap_u);tn_M(c.iw_xtap_ul);tn_M(c.iw_xtap_ld);tn_M(c.iw_xtap_rd);tn_M(c.iws_tap);tn_M(c.iws_tap_l);tn_M(c.iws_tap_u);tn_M(c.iws_tap_ul);
tn_M(c.iws_tap_ld);tn_M(c.iws_tap_rd);var j,m,l,g;c=a.getClientRects();var i=Array(c.length),n=tn_ga(a);a=c[0].top-n.y;for(var k=0;k<c.length;++k){i[k]={left:c[k].left,right:c[k].right,top:c[k].top,bottom:c[k].bottom};if(k>0&&i[k].bottom==i[k-1].bottom)if(i[k].left==i[k-1].right){i[k].left=i[k-1].left;i[k].top=tn_O(i[k].top,i[k-1].top)}else if(i[k].right==i[k-1].left){i[k].right=i[k-1].right;i[k].top=tn_O(i[k].top,i[k-1].top)}if(!j||i[k].left<=j.left)j=i[k];if(!m||i[k].right>=m.right)m=i[k];if(!l||
i[k].top<=l.top)l=i[k];if(!g||i[k].bottom>=g.bottom)g=i[k]}if(this.m&&21+d+6+12+m.right<f)return this.p(new tn_d(j.left+b,m.top-a,m.right-j.left,m.bottom-m.top));else if(this.m&&18+d+21<j.left)return this.p(new tn_d(j.left+b,j.top-a,m.right-j.left,j.bottom-j.top));else{if(this.S&&21+e+6+12+(this.f.length>1?20:0)>n.y-(this.Ca?h:0)){d=this.m;this.m=tn_b;l=this.p(new tn_d(g.left+b,l.top-a,g.right-g.left,g.bottom-l.top))}else{d=this.m;this.m=tn_b;l=this.p(new tn_d(l.left+b,l.top-a,l.right-l.left,g.bottom-
l.top))}this.m=d;return l}};
tn__.prototype.p=function(a,b){var c=this.A(),d=this.g,e=c.width,f=c.height,h=document.body.scrollWidth,j=document.documentElement.scrollLeft||window.scrollX||document.body.scrollLeft,m=document.documentElement.scrollTop||window.scrollY||document.body.scrollTop;tn_M(d.iw_xtap);tn_M(d.iw_xtap_l);tn_M(d.iw_xtap_u);tn_M(d.iw_xtap_ul);tn_M(d.iw_xtap_ld);tn_M(d.iw_xtap_rd);tn_M(d.iws_tap);tn_M(d.iws_tap_l);tn_M(d.iws_tap_u);tn_M(d.iws_tap_ul);tn_M(d.iws_tap_ld);tn_M(d.iws_tap_rd);var l=0;c=0;var g,i,n,
k,o,p=0,q=this.m;if(q&&21+e+6+12+a.x+a.w<j+h){i=tn_;f=d.iw_xtap_ld;m=d.iws_tap_ld}else if(q&&18+e+21+j<a.x){n=tn_;f=d.iw_xtap_rd;m=d.iws_tap_rd;c=5}else{if(this.S&&21+f+6+12+(this.f.length>1?20:0)+(this.Ca?m:0)>a.y){f=d.iw_xtap_u;m=d.iws_tap_u;l=0;g=tn_}else{f=d.iw_xtap;m=d.iws_tap;l=0}if(tn_J(a.x+a.w/2)+32+6+12>j+h){if(f==d.iw_xtap_u){f=d.iw_xtap_ul;m=d.iws_tap_ul}else{f=d.iw_xtap_l;m=d.iws_tap_l}c=5;l=32}k=tn_J((e-32)/2);if(this.Aa)if(k+6+12+l+j>a.x+tn_J(a.w/2)){k=a.x+tn_J(a.w/2)-6-12-l-j;if(k<
0){p=tn_O(-k,tn_J(a.w/2));k=0}k=k}else if(a.x+tn_J(a.w/2)-l+e-k+6+12>j+h){if(g){f=d.iw_xtap_ul;m=d.iws_tap_ul}else{f=d.iw_xtap_l;m=d.iws_tap_l}c=5;l=32;k=a.x+tn_J(a.w/2)-l+e+6+12-h-j;if(k>e-32){p=tn_P(e-32-k,-tn_J(a.w/2));k=e-32}k=k}o=e-32-k}tn_N(f);tn_N(m);this.Xa=i?0:n?6+e+21:6+k+l;e=this.ba=b||tn_U.ZERO;p=this.Xa-p;d=i||n?6:g?0:this.ra().height+(this.f.length>1?20:0);p-=e.width;d-=e.height;this.cb=e=new tn_c(a.x+(i?a.w:n?0:a.w/2)-p,a.y+(i||n?a.h/2:g?a.h:0)-d);tn_G(this.e,e);tn_G(this.i,e);this.da=
a;this.Ea=undefined;return this.Ga(i,n,g,k,o,f,m,c)};
tn__.prototype.Ga=function(a,b,c,d,e,f,h,j){var m=!(a||b||c);this.R=f;this.P=h;var l=this.A(),g=this.g,i=l.width,n=l.height,k=this.f.length>1?this.v:0;if(c){tn_K(g.iw_n1,tn_P(d,0));tn_K(g.iw_n2,tn_P(e,0));tn_K(g.iw_s1,i-k);tn_K(g.iw_s2,0);tn_K(g.iws_n1,tn_P(d,0));tn_K(g.iws_n2,tn_P(e,0));tn_K(g.iws_s1,i-k);tn_K(g.iws_s2,0)}else if(m){tn_K(g.iw_n1,i-k);tn_K(g.iw_n2,0);tn_K(g.iw_s1,tn_P(d,0));tn_K(g.iw_s2,tn_P(e,0));tn_K(g.iws_n1,i-k);tn_K(g.iws_n2,0);tn_K(g.iws_s1,tn_P(d,0));tn_K(g.iws_s2,tn_P(e,0))}else{tn_K(g.iw_n1,
i);tn_K(g.iw_n2,0);tn_K(g.iw_s1,i-k);tn_K(g.iw_s2,0);tn_K(g.iws_n1,i);tn_K(g.iws_n2,0);tn_K(g.iws_s1,i-k);tn_K(g.iws_s2,0)}tn_$c(g.iw_c,l);if(a){tn_L(g.iw_w,tn_P(n-32,0));tn_L(g.iw_e,tn_P(n,32));tn_L(g.iws_w,tn_P(n-32,0));tn_L(g.iws_e,tn_P(n,32))}else if(b){tn_L(g.iw_e,tn_P(n-32,0));tn_L(g.iw_w,tn_P(n,32));tn_L(g.iws_e,tn_P(n-32,0));tn_L(g.iws_w,tn_P(n,32))}else{tn_L(g.iw_w,n);tn_L(g.iw_e,n);tn_L(g.iws_w,n);tn_L(g.iws_e,n)}e=a?15:0;l=e+5-2;var o=e+6,p=o+5,q=o+i,r=q+5,s=a?0:b?q:o+d,B=s+j,A=s+32,C=
A+5;i=c?15:!a&&!b&&this.f.length>1?20:0;var y=i+5-2,t=i+6,z=t+5,u=t+(a||b?tn_P(n,32):n),w=u+5;n=c||a||b?u:0;j=n+5-(c||a||b?0:2);d=c||a||b?u+6-1:0;var D=new tn_c(o,u),E=new tn_c(p,w),F=new tn_c(o,i),G=new tn_c(p,y);tn_G(g.iw_nw,new tn_c(e,i));tn_G(g.iws_nw,new tn_c(l,y));if(m){tn_G(g.iw_n1,new tn_c(o+k,i));tn_G(g.iws_n1,new tn_c(p+k,y));tn_G(g.iw_s1,D);tn_G(g.iws_s1,E);tn_G(g.iw_s2,new tn_c(A,u));tn_G(g.iws_s2,new tn_c(C,w));tn_M(g.iws_tab_dl);tn_M(g.iws_tab_dr);tn_N(g.iws_tab_l);tn_N(g.iws_tab_r);
tn_G(g.iws_tab_l,new tn_c(l,j));tn_G(g.iws_tab_r,new tn_c(p+k-14,j))}else{tn_G(g.iw_n1,F);tn_G(g.iws_n1,G);tn_G(g.iw_s2,D);tn_G(g.iws_s2,E);tn_G(g.iw_s1,new tn_c(o+k,u));tn_G(g.iws_s1,new tn_c(p+k,w));tn_N(g.iws_tab_dl);tn_N(g.iws_tab_dr);tn_M(g.iws_tab_l);tn_M(g.iws_tab_r);tn_G(g.iws_tab_dl,new tn_c(l,j));tn_G(g.iws_tab_dr,new tn_c(p+k-14,j))}if(c){tn_G(g.iw_n2,new tn_c(A,i));tn_G(g.iws_n2,new tn_c(C,y))}else{tn_G(g.iw_n2,F);tn_G(g.iws_n2,G)}tn_G(g.iw_ne,new tn_c(q,i));tn_G(g.iws_ne,new tn_c(r,y));
tn_G(g.iw_w,new tn_c(e,t+(a?32:0)));tn_G(g.iws_w,new tn_c(l,z+(a?32:0)));tn_G(g.iw_c,new tn_c(o,t));tn_G(g.iws_c,new tn_c(p,z));tn_K(g.iw_c,q-o);tn_L(g.iw_c,u-t);tn_K(g.iws_c,r-p);tn_L(g.iws_c,w-z);tn_G(g.iw_e,new tn_c(q,t+(b?32:0)));tn_G(g.iws_e,new tn_c(r,z+(b?32:0)));tn_G(g.iw_sw,new tn_c(e,u));tn_G(g.iws_sw,new tn_c(l,w));tn_G(g.iw_se,new tn_c(q,u));tn_G(g.iws_se,new tn_c(r,w));if(a){tn_G(f,new tn_c(0,t));tn_G(h,new tn_c(0,t))}else if(b){tn_G(f,new tn_c(q,t));tn_G(h,new tn_c(r,t))}else if(c){tn_G(f,
new tn_c(s,0));tn_G(h,new tn_c(B,0))}else{tn_G(f,new tn_c(s,u));tn_G(h,new tn_c(B,w))}a=this.aa=="rtl"?0+o:q-14+0;b=t-0;tn_G(g.close,new tn_c(a,b));if(g.close.style.visibility!="hidden")if(this.aa=="rtl")a+=16;else a-=16;a=new tn_c(a,b);tn_G(g.maximize,a);tn_G(g.restore,a);this.ga=new tn_c(e+8,i+8);for(a=0;a<this.l.length;a++){b=this.l[a];tn_G(b,this.ga)}if(this.f.length<2){tn_M(g.iws_tab_l);tn_M(g.iws_tab_r);tn_M(g.iws_tab_dl);tn_M(g.iws_tab_dr);tn_N(g.iw_sw);tn_N(g.iws_sw);tn_N(g.iw_nw);tn_N(g.iws_nw)}else{if(m){tn_M(g.iw_nw);
tn_M(g.iws_nw);tn_N(g.iw_sw);tn_N(g.iws_sw)}else{tn_M(g.iw_sw);tn_M(g.iws_sw);tn_N(g.iw_nw);tn_N(g.iws_nw)}for(a=0;a<this.f.length;++a){g=this.f[a];i=g.images;f=g.textWidth;b=g.labelNode;p=b.style;var v;if(a>0)v=this.ha[a-1];tn_M(i.iw_tabback_dl);tn_M(i.iw_tabback_dm);tn_M(i.iw_tabback_dr);tn_M(i.iw_tabback_l);tn_M(i.iw_tabback_m);tn_M(i.iw_tabback_r);tn_M(i.iw_tab_dl);tn_M(i.iw_tab_dm);tn_M(i.iw_tab_dr);tn_M(i.iw_tab_l);tn_M(i.iw_tab_m);tn_M(i.iw_tab_r);tn_M(i.iws_tab_m);tn_M(i.iws_tab_dm);if(v){tn_M(v.iws_tab_do);
tn_M(v.iws_tab_o)}else{tn_M(i.iw_tab_1l);tn_M(i.iw_tab_1dl);tn_M(i.iw_tabback_1l);tn_M(i.iw_tabback_1dl);tn_M(i.iws_tab_1l);tn_M(i.iws_tab_1dl)}var x;c=this.e.style.zIndex;if(m){if(this.s==a){h=a==0?i.iw_tab_1l:i.iw_tab_l;k=i.iw_tab_m;o=i.iw_tab_r;++c}else{h=a==0?i.iw_tabback_1l:i.iw_tabback_l;k=i.iw_tabback_m;o=i.iw_tabback_r}i=i.iws_tab_m;if(v)x=v.iws_tab_o;p.paddingTop=tn_I(4);p.paddingBottom=tn_I(0)}else{if(this.s==a){h=a==0?i.iw_tab_1dl:i.iw_tab_dl;k=i.iw_tab_dm;o=i.iw_tab_dr;++c}else{h=a==0?
i.iw_tabback_1dl:i.iw_tabback_dl;k=i.iw_tabback_dm;o=i.iw_tabback_dr}i=i.iws_tab_dm;if(v)x=v.iws_tab_do;p.paddingTop=tn_I(4);p.paddingBottom=""}tn_N(h);tn_N(k);tn_N(o);tn_N(i);p=g.offset+(a==0?6:11);tn_G(h,new tn_c(e+g.offset,n));tn_G(k,new tn_c(e+p,n));tn_K(k,f);tn_G(i,new tn_c(l+2+p,j));tn_K(i,f);tn_G(o,new tn_c(e+p+f,n));if(x){tn_N(x);tn_G(x,new tn_c(l+p-14+2,j));x.parentNode||tn_H(this.i,x)}h.style.zIndex=c;k.style.zIndex=c;o.style.zIndex=c;f=f+2+3;tn_K(b,f);tn_G(b,new tn_c(e+p-2,d));tn_N(b);
b.style.zIndex=c+1;!b.parentNode&&g.textWidth>0&&tn_H(this.e,b)}}};tn__.prototype.C=function(){if(this.Ea)this.F(this.Ea,this.ba);else this.da&&this.p(this.da,this.ba)};tn__.prototype.A=function(){return new tn_U(tn_P(this.q.width,this.v),this.q.height)};tn__.prototype.reset=function(a,b,c,d,e){this.u(c,b,e);this.p(a,d);this.show();tn_bd(this.g.restore)};tn__.prototype.hide=function(){this.R&&tn_M(this.R);this.P&&tn_M(this.P);tn_M(this.e);tn_M(this.i)};
tn__.prototype.show=function(){if(this.ya()){tn_N(this.e);tn_N(this.i);this.R&&tn_N(this.R);this.P&&tn_N(this.P)}};tn__.prototype.Pa=function(){this.bb=tn_};tn__.prototype.ya=function(){return this.e.style.display=="none"};tn__.prototype.Ka=function(a){if(a!=this.s){this.ea(a);var b=this.l;tn_pd(b,tn_M);tn_N(b[a]);var c=this;window.setTimeout(function(){c.C()},0)}};tn__.prototype.Fa=function(){tn_X(this,tn_Vd)};
tn__.prototype.maximize=function(a){if(!this.M){tn_X(this,tn_Wd);tn_cd(this.g.restore);this.Ra=this.q;this.ab=this.f;this.$a=this.s;this.o=this.o||new tn_U(628,598);var b=new tn_U(4+this.o.width,4+this.o.height);if(tn_S.k())b.width+=1;this.$(b,a)}};tn__.prototype.Na=function(a){this.o=this.H(a)};tn__.prototype.restore=function(a){if(this.M){tn_X(this,tn_Xd);tn_bd(this.g.restore);this.u(this.o,this.ab,this.$a);this.Va=this.Ra;this.$(this.Ra,a)}};
tn__.prototype.$=function(a,b){this.Z=new tn_qe(b===tn_?1:10);this.K=this.q;this.ta=a;this.V()};tn__.prototype.V=function(){var a=this.Z.next();this.Z.more()&&tn_id(this,this.V,10);var b=this.K.width+(this.ta.width-this.K.width)*a;a=this.K.height+(this.ta.height-this.K.height)*a;this.O(new tn_U(b,a));this.C();this.Ta();this.Z.more()||this.sa()};tn__.prototype.sa=function(){if(this.M){this.M=tn_b;tn_X(this,tn_Zd)}else{this.M=tn_;tn_X(this,tn_Yd);this.o&&this.Da&&this.u(this.o,this.Da,this.Wa)}};
tn__.prototype.O=function(a){return a=this.q=this.H(a)};tn__.prototype.pa=function(a){if(tn_S.type==1)tn_ae(a);else{var b=tn_pe(a,this.e);b.y<=this.Y()&&tn_ae(a)}};tn__.prototype.X=function(a){if(tn_S.type==1)tn_be(a);else{var b=tn_pe(a,this.e);if(b.y<=this.Y())a.cancelDrag=tn_}};tn__.prototype.Y=function(){return this.A().height+12};tn__.prototype.ra=function(){var a=this.A();return new tn_U(a.width+12,a.height+21+6)};
tn__.prototype.u=function(a,b,c){this.na();this.Va=a;a=new tn_U(4+a.width,4+a.height);if(tn_S.k())a.width+=1;var d=this.O(a),e=[];this.f=e;var f=c||0;a=new tn_U(d.width+-4,d.height+-4);var h=this.ga,j=this.l=[];for(c=0;c<b.length;c++){var m=tn_F("div",this.e,h,a);tn_dd(m);c!=f&&tn_M(m);m.style.zIndex=10;tn_H(m,b[c].contentElem);j.push(m)}if(b.length>1){a=[];h=new tn_U(11,26);j=new tn_U(14,26);this.xa();for(c=0;c<b.length;++c){var l={images:b[c].images||{},textWidth:b[c].textWidth||0,offset:b[c].offset||
0,name:b[c].name,contentElem:b[c].contentElem,onclick:b[c].onclick},g=l.images;tn_te(g,this.e,[["iw_tabback_dm",1,26,0,0],["iw_tabback_m",1,26,0,0],["iw_tab_dm",1,26,0,0],["iw_tab_m",1,26,0,0]]);tn_0(g,this.e,"iw_tabback_dl",h);tn_0(g,this.e,"iw_tabback_dr",j);tn_0(g,this.e,"iw_tabback_l",h);tn_0(g,this.e,"iw_tabback_r",j);tn_0(g,this.e,"iw_tab_dl",h);tn_0(g,this.e,"iw_tab_dr",j);tn_0(g,this.e,"iw_tab_l",h);tn_0(g,this.e,"iw_tab_r",j);tn_te(g,this.i,[["iws_tab_dm",1,28,0,0],["iws_tab_m",1,28,0,0]]);
m=function(k,o){tn_M(o);k.Q.push(o)};if(c==0){var i=new tn_U(6,26);tn_0(g,this.e,"iw_tab_1dl",i);tn_0(g,this.e,"iw_tab_1l",i);tn_0(g,this.e,"iw_tabback_1dl",i);tn_0(g,this.e,"iw_tabback_1l",i);i=new tn_U(8,28);tn_0(g,this.i,"iws_tab_1dl",i);tn_0(g,this.i,"iws_tab_1l",i);m(this,g.iw_tab_1dl);m(this,g.iw_tab_1l);m(this,g.iw_tabback_1dl);m(this,g.iw_tabback_1l);m(this,g.iws_tab_1dl);m(this,g.iws_tab_1l)}m(this,g.iw_tabback_dl);m(this,g.iw_tabback_dm);m(this,g.iw_tabback_dr);m(this,g.iw_tabback_l);m(this,
g.iw_tabback_m);m(this,g.iw_tabback_r);m(this,g.iw_tab_dl);m(this,g.iw_tab_dm);m(this,g.iw_tab_dr);m(this,g.iw_tab_l);m(this,g.iw_tab_m);m(this,g.iw_tab_r);m(this,g.iws_tab_dm);m(this,g.iws_tab_m);g=document.createElement("div");l.labelNode=g;tn_L(g,20);i=g.style;tn_dd(g);i.fontWeight="bold";i.fontFamily="Arial,sans-serif";i.fontSize=tn_I(12);i.textAlign="center";i.display="inline";tn_ue(g);tn_ad(l.name,g);(function(k,o,p,q){tn_$d(q,k,function(){k.Ka(o);p&&p()})})(this,c,b[c].onclick,g);this.Q.push(g);
a.push(g);this.f.push(l);if(c>0){l={};g=new tn_U(14,28);tn_0(l,this.i,"iws_tab_do",g);tn_0(l,this.i,"iws_tab_o",g);m(this,l.iws_tab_do);m(this,l.iws_tab_o);this.ha.push(l)}}var n=this;tn_Gd(a,function(k){var o;if(k.length==e.length){for(var p=0;p<k.length;++p){var q=o=e[p];if(k[p].width!=0)q.textWidth=tn_P(0,k[p].width-2-3);tn_N(q.labelNode);tn_H(n.e,q.labelNode);if(p>0){var r=e[p-1];q.offset=r.offset+r.textWidth+(p==1?6:11)+14-11}}n.v=o.offset+o.textWidth+ +14+11-6;if(n.v+30>d.width){n.O(new tn_U(n.v+
30,d.height));k=new tn_U(n.v+30+-4,d.height+-4);for(p=0;p<n.l.length;++p)tn_$c(n.l[p],k)}}n.ea(f);n.C()})}else{l={images:b[0].images||{},textWidth:b[0].textWidth||0,offset:b[0].offset||0,name:b[0].name,contentElem:b[0].contentElem,onclick:b[0].onclick};this.f.push(l);this.C()}};tn__.prototype.Ta=function(){for(var a=new tn_U(this.q.width+-4,this.q.height+-4),b=0;b<this.l.length;b++){var c=this.l[b];tn_$c(c,a)}};tn__.prototype.Ma=function(a,b,c){this.o=a;this.Da=b;this.Wa=c;tn_cd(this.g.maximize)};
tn__.prototype.na=function(){var a=this.l;tn_pd(a,tn_R);tn_Bd(a);a=this.Q;tn_pd(a,tn_R);tn_Bd(a);this.s=0};tn__.prototype.H=function(a){return new tn_U(tn_P(a.width,32),tn_P(a.height,0))};tn__.prototype.xa=function(){this.Q=[];this.ha=[];this.v=0};tn__.prototype.ea=function(a){tn_ue(this.f[this.s].labelNode);this.s=a;tn_ve(this.f[a].labelNode)};function tn_ve(a){var b=a.style;b.color="";b.textDecoration="";tn_Q(a,"")}
function tn_ue(a){var b=a.style;b.color="#0000cc";b.textDecoration="underline";tn_Q(a,"pointer")}function tn_te(a,b,c){b=tn_F("div",b,tn_a,tn_a,tn_b,tn_);for(var d=0;d<c.length;d++){var e=c[d],f=new tn_U(e[1],e[2]),h=new tn_c(e[3],e[4]),j=tn_6c+e[0]+".png";f=tn_Hd(j,b,h,f,tn_,tn_);a[e[5]||e[0]]=f}return b}
function tn_0(a,b,c,d,e,f){if(tn_S.type==1&&tn_S.version<7){b=tn_Hd(tn_6c+c+(f?".gif":".png"),b,new tn_c(0,0),d,tn_,tn_);return a[e||c]=b}if(!tn_re){tn_re=tn_;d=document.createElement("link");d.rel="stylesheet";d.type="text/css";d.href=tn_6c+"iw_sprite.css";document.getElementsByTagName("head")[0].appendChild(d)}d=document.createElement("div");d.className="SPRITE_"+c;d.style.overflow="hidden";b.appendChild(d);return a[e||c]=d};if(window.jstiming){window.jstiming.ma={};window.jstiming.Za=1;var tn_we=function(a,b,c){var d=a.t[b],e=a.t.start;if(d&&(e||c)){d=a.t[b][0];e=c!=undefined?c:e[0];return d-e}},tn_xe=function(a,b,c){var d="";if(window.jstiming.pt){d+="&srt="+window.jstiming.pt;delete window.jstiming.pt}try{if(window.external&&window.external.tran)d+="&tran="+window.external.tran;else if(window.gtbExternal&&window.gtbExternal.tran)d+="&tran="+window.gtbExternal.tran();else if(window.chrome&&window.chrome.csi)d+="&tran="+
window.chrome.csi().tran}catch(e){}var f=window.chrome;if(f)if(f=f.loadTimes){if(f().wasFetchedViaSpdy)d+="&p=s";if(f().wasNpnNegotiated)d+="&npn=1";if(f().wasAlternateProtocolAvailable)d+="&apa=1"}if(a.Ua)d+="&"+a.Ua;f=a.t;var h=f.start,j=[],m=[],l;for(l in f)if(l!="start")if(l.indexOf("_")!=0){var g=f[l][1];if(g)f[g]&&m.push(l+"."+tn_we(a,l,f[g][0]));else h&&j.push(l+"."+tn_we(a,l))}delete f.start;if(b)for(var i in b)d+="&"+i+"="+b[i];return a=[c?c:"http://csi.gstatic.com/csi","?v=3","&s="+(window.jstiming.sn||
"translate")+"&action=",a.name,m.length?"&it="+m.join(","):"","",d,"&rt=",j.join(",")].join("")};window.jstiming.report=function(a,b,c){a=tn_xe(a,b,c);if(!a)return"";b=new Image;var d=window.jstiming.Za++;window.jstiming.ma[d]=b;b.onload=b.onerror=function(){delete window.jstiming.ma[d]};b.src=a;b=tn_a;return a}};var _infowindowVersion=1,_redirectUrl,tn_1,tn_2=tn_a,tn_3,tn_ye,tn_ze,tn_Ae=tn_b,tn_Be=tn_b,tn_4=tn_b,tn_5=tn_b,tn_6={};tn_6.right="left";tn_6.left="right";tn_6.ltr="rtl";tn_6.rtl="ltr";var tn_Ce="/community",tn_De=tn_Ce+"/edit",tn_7,tn_Ee,tn_Fe,tn_Ge,tn_8,tn_He;function tn_Ie(a){return a.substring(0,1).toUpperCase()+a.substring(1)}
var _intlStrings={_originalText:"Original Text:",_interfaceDirection:"ltr",_interfaceAlign:"left",_langpair:"",_currentBy:"",_unknown:"unknown",_suggestTranslation:"Suggest a translation",_submit:"Submit",_feedbackUrl:"http://translate.google.com/translate_suggestion",_suggestThanks:"Thank you for helping us improve the quality of our translations.",_reverse:tn_b};
function tn_Je(a){if(a.nodeType==3)return a.nodeValue;else if(a.nodeType==1){for(var b=new String,c=0;c<a.childNodes.length;++c)b+=tn_Je(a.childNodes[c]);return b}}function tn_Ke(a,b){if(a)if(b.nodeType==3)a.appendChild(document.createTextNode(b.nodeValue));else if(b.nodeType==1){var c;if(b.nodeName==="a"||b.nodeName==="A"){c=document.createElement("a");var d=b.getAttribute("href");d&&c.setAttribute("href",d);a.appendChild(c)}else c=a;for(d=0;d<b.childNodes.length;++d)tn_Ke(c,b.childNodes[d])}}
function tn_Le(){for(var a=document.getElementsByTagName("span"),b=0;b<a.length;++b){var c=a[b];if(c.className=="google-tr-info"){var d=tn_Me(c.firstChild.nodeValue,",",3);if(d&&d[1]!=="0")c.parentNode.className="google-tr-highlight"}}}
function _setupIW(){if(!tn_Ae){tn_1=new tn__;tn_3=document.createElement("div");tn_3.id="google-infowindow";tn_ye=document.createElement("span");tn_3.onmouseover=tn_Ne;tn_3.onmouseout=tn_Oe;document.body.appendChild(tn_ye);document.body.appendChild(tn_3);var a=document.createElement("div");document.body.appendChild(a);tn_M(a);a.innerHTML='<iframe id="google-feedback-frame" name="google-feedback-frame"></iframe>';tn_1.create(tn_3,tn_ye);tn_3.firstChild.style.zIndex=2147483647;tn_ye.firstChild.style.zIndex=
2147483647;tn_1.G(tn_);tn_1.za(tn_);tn_1.Ba(tn_);tn_1.ja(tn_);tn_1.ka(tn_b);tn_1.La(_intlStrings._interfaceDirection);tn_3d(tn_1,tn_Vd,function(){tn_Oe(tn_);tn_5&&tn_Pe(tn_b)});_infowindowVersion==2&&tn_Le();tn_Ae=tn_}}var tn_9=tn_a;function tn_Ne(){tn_Be=tn_;tn_Qe(tn_2)}
function tn_Qe(a){if(a){if(tn_9!==tn_a){window.clearTimeout(tn_9);tn_9=tn_a}if(!tn_4)if(tn_2==a){if(!tn_5){tn_ze=tn_2.style.backgroundColor;tn_2.style.backgroundColor="#E6ECF9"}}else{if(tn_5){tn_1.restore(tn_);tn_5=tn_b}for(var b,c=a.cloneNode(tn_),d=a.childNodes.length-1;d>=0;--d)if(a.childNodes[d].className=="google-src-text"){b=a.childNodes[d].cloneNode(tn_);c.removeChild(c.childNodes[d]);b.className="google-src-active-text"}else a.childNodes[d].className=="google-tr-info"&&c.removeChild(c.childNodes[d]);
if(b){tn_1.G(tn_);tn_ze=a.style.backgroundColor;a.style.backgroundColor="#E6ECF9";var e=document.createElement("div"),f=document.createElement("div"),h=document.createElement("img"),j=document.createElement("div");j.appendChild(h);h.width=48;h.height=17;h.border=0;h.style.padding="0px";h.style.border="0px solid black";j.style.margin="0px";j.style.marginBottom="-17px";j.style.padding="0px";j.style.textAlign=tn_6[_intlStrings._interfaceAlign];h.src="http://www.google.com/images/logo_smallest.png";h.style["margin"+
tn_Ie(_intlStrings._interfaceAlign)]="6px";h.style["margin"+tn_Ie(tn_6[_intlStrings._interfaceAlign])]=tn_I(18);e.appendChild(j);e.appendChild(f);f.appendChild(document.createTextNode(_intlStrings._originalText));f.style.color="#333";f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.fontWeight="bold";f.style.fontSize="12px";f.style.minHeight="19px";f.style.fontFamily="arial,sans-serif";f.style["margin"+tn_Ie(tn_6[_intlStrings._interfaceAlign])]=
tn_I(72);f=document.createElement("div");f.className="google-src-active-text";f.style.lineHeight="19px";f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;tn_Ke(f,b);e.appendChild(f);e.style.zIndex=2147483647;if(_intlStrings._langpair.length==0){tn_2=a;tn_Fd(e,function(s){tn_1.hide();tn_1.u(s,[new tn_se(_intlStrings._originalText,e)]);tn_1.F(tn_2);tn_1.show()},(document.width||document.body.scrollWidth)/2)}else{h=e.cloneNode(tn_);var m=document.createElement("div");
m.appendChild(h);var l=document.createElement("div");h=document.createElement("span");f=document.createElement("div");f.style.direction=_intlStrings._interfaceDirection;f.style.textAlign=_intlStrings._interfaceAlign;f.style.marginTop=tn_I(5);l.appendChild(f);j=document.createElement("img");j.src="http://www.google.com/images/zippy_plus_sm.gif";j.width=12;j.height=12;j.border=0;j.style.border="none";j.style.verticalAlign="middle";f.appendChild(j);f.appendChild(document.createTextNode(" "));f.appendChild(h);
h.appendChild(document.createTextNode(_intlStrings._suggestTranslation));h.style.direction=_intlStrings._interfaceDirection;h.style.textAlign=_intlStrings._interfaceAlign;h.style.color="#0000CC";h.style.textDecoration="underline";h.style.fontFamily="arial,sans-serif";h.style.fontSize="12px";f.onclick=tn_Re;tn_Q(h,"pointer");e.appendChild(l);var g=document.createElement("div");h=document.createElement("div");j=document.createElement("span");h.style.direction=_intlStrings._interfaceDirection;h.style.textAlign=
_intlStrings._interfaceAlign;h.style.marginTop=tn_I(5);h.style.marginBottom=tn_I(6);g.appendChild(h);var i=document.createElement("img");i.src="http://www.google.com/images/zippy_minus_sm.gif";i.width=12;i.height=12;i.border=0;i.style.border="none";i.style.verticalAlign="middle";h.appendChild(i);h.appendChild(document.createTextNode(" "));h.appendChild(j);j.appendChild(document.createTextNode(_intlStrings._suggestTranslation));j.style.direction=_intlStrings._interfaceDirection;j.style.textAlign=_intlStrings._interfaceAlign;
j.style.color="#0000CC";j.style.textDecoration="underline";j.style.fontFamily="arial,sans-serif";j.style.fontSize="12px";h.onclick=function(){tn_Pe(tn_)};tn_Q(j,"pointer");tn_2=a;if(_infowindowVersion==1){var n=document.createElement("div");f=document.createElement("form");f.style.marginBottom="0px";f.style.paddingBottom="0px";f.target="google-feedback-frame";f.method="post";f.action=_intlStrings._feedbackUrl;n.appendChild(f);a=document.createElement("input");a.type="hidden";a.name="gtrans";f.appendChild(a);
if(_intlStrings._reverse){h=tn_Je(c);c=tn_Je(b)}else{c=tn_Je(c);h=tn_Je(b)}a.value=c;b=document.createElement("input");b.type="hidden";b.value=h;b.name="text";f.appendChild(b);b=document.createElement("input");b.name="langpair";b.type="hidden";b.value=_intlStrings._langpair;f.appendChild(b);b=document.createElement("input");b.name="u";b.type="hidden";b.value=tn_$("u");f.appendChild(b);b=document.createElement("input");b.name="oe";b.type="hidden";if(document.charset){b.value=document.charset;f.appendChild(b)}else if(document.characterSet){b.value=
document.characterSet;f.appendChild(b)}else if(a=tn_$("oe")){f.appendChild(b);b.value=a}var k=document.createElement("textarea");k.rows=3;k.name="utrans";k.value=c;f.appendChild(k);b=document.createElement("div");b.style.direction=_intlStrings._interfaceDirection;b.style.textAlign=tn_6[_intlStrings._interfaceAlign];b.style.marginTop=tn_I(6);b.style.marginBottom="0px";f.appendChild(b);c=document.createElement("input");c.type="submit";c.value=_intlStrings._submit;b.appendChild(c);var o=document.createElement("div");
o.appendChild(document.createElement("hr"));o.appendChild(document.createTextNode(_intlStrings._suggestThanks));o.style.direction=_intlStrings._interfaceDirection;o.style.textAlign=_intlStrings._interfaceAlign;o.style.fontFamily="arial,sans-serif";o.style.fontSize="12px";o.style.overflow="auto";o.style.marginTop="10px";tn_M(o);g.appendChild(n);m.appendChild(g);m.appendChild(o);f.onsubmit=function(){window.setTimeout(function(){tn_M(g);tn_N(o)},1);tn_4=tn_b;return tn_};tn_Gd([m,e],function(s){k.style.width=
tn_I(s[0].width-1);tn_1.hide();tn_1.u(s[1],[new tn_se(_intlStrings._originalText,e)]);tn_1.Ma(s[0],[new tn_se(_intlStrings._originalText,m)]);tn_1.F(tn_2);tn_1.G(tn_);tn_1.show()},(document.width||document.body.scrollWidth)/2)}else if(_infowindowVersion==2){(j=tn_$("rurl"))||(j="translate.google.com");h=_intlStrings._langpair.split("|",2);i="hl="+tn_$("hl")+"&sl="+h[0]+"&tl="+h[1];try{tn_7=document.createElement('<iframe name="google-edit-frame">')}catch(p){tn_7=document.createElement("iframe")}tn_7.id=
"google-edit-frame";tn_7.name="google-edit-frame";tn_7.style.margin=0;tn_7.style.padding=0;tn_7.frameBorder=0;tn_7.width=650;tn_7.height=350;e.appendChild(tn_7);h=e.cloneNode(tn_);for(d=0;d<a.childNodes.length;++d)if(a.childNodes[d].className=="google-tr-info"){n=a.childNodes[d].firstChild.nodeValue;break}if(n)if((a=tn_Me(n,",",3))&&a[1]!=="0"){tn_7.src="http://translate.google.com"+tn_Ce+"/authorinfo?"+i+"&uid="+a[0]+"&date="+a[1];tn_7.height=15}else tn_7.style.display="none";else tn_7.style.display=
"none";if(!tn_Ee){try{tn_Ee=document.createElement('<iframe name="google-send-frame">')}catch(q){tn_Ee=document.createElement("iframe")}tn_Ee.name="google-send-frame";window.document.body.appendChild(tn_Ee);tn_Ee.style.display="none";a="http://"+j+tn_Ce+"/send?domain="+window.location.host;if(d=tn_$("hl"))a+="&hl="+d;tn_Ee.src=a}var r=document.createElement("form");r.style.display="none";r.target="google-edit-frame";r.method="post";a="http://"+j+tn_De+"?"+i;j=new Date;a+="&ctz="+j.getTimezoneOffset();
e.appendChild(r);i=document.createElement("input");i.name="sentence";i.type="hidden";i.value=_intlStrings._reverse?c.innerHTML:b.innerHTML;if(j=document.documentMode){i.value=encodeURIComponent(i.value);a+="&escape=1"}r.appendChild(i);r.action=a;if(!n&&!tn_$("mt")){n=document.createElement("input");n.type="hidden";n.name="showtrans";n.value=_intlStrings._reverse?b.innerHTML:c.innerHTML;if(j)n.value=encodeURIComponent(n.value);r.appendChild(n)}b=document.createElement("input");b.name="u";b.type="hidden";
b.value=tn_$("u");r.appendChild(b);b=document.createElement("input");b.name="domain";b.type="hidden";b.value=window.location.host;r.appendChild(b);f.onclick=function(){if(_redirectUrl)if(_redirectUrl.indexOf("/community/login?")>0)window.open(_redirectUrl);else window.top.location=_redirectUrl;else{r.submit();l.parentNode.replaceChild(g,l);tn_Re()}};tn_Fe=l;tn_Ge=g;tn_Gd([h,e],function(s){tn_1.hide();tn_1.u(s[1],[new tn_se(_intlStrings._originalText,e)]);tn_1.Na(s[0]);tn_1.F(tn_2);tn_1.G(tn_);tn_1.show()},
650)}}}}}}function tn_$(a){var b=window.location.search.substring(1);b=b.split("&");for(var c=0;c<b.length;c++){var d=b[c].split("=");if(d[0].toLowerCase()==a&&d.length>0)return window.unescape(d[1])}return""}function tn_Se(a){if(tn_Ae){tn_Be=tn_;if(!tn_4){if(tn_9!==tn_a){window.clearTimeout(tn_9);tn_9=tn_a}if(tn_2==a){tn_ze=tn_2.style.backgroundColor;tn_2.style.backgroundColor="#E6ECF9"}else tn_9=window.setTimeout(function(){tn_Qe(a)},500)}}}
function tn_Oe(a){if(tn_Ae){if(a!==tn_)tn_Be=tn_b;if(!tn_4){if(tn_2&&tn_2.style)tn_2.style.backgroundColor=tn_ze;if(tn_9){window.clearTimeout(tn_9);tn_9=tn_a}if(a!==tn_)tn_9=window.setTimeout(tn_Te,250);else tn_Te()}}}function tn_Te(){if(!tn_4){tn_1.hide();if(tn_5){tn_1.restore(tn_);tn_5=tn_b}tn_2=tn_a}}function tn_Re(){tn_5=tn_4=tn_;var a=tn_3d(tn_1,tn_Yd,function(){if(_infowindowVersion==2){tn_7.height=350;tn_7.style.display="block"}tn_4d(a)});tn_1.maximize()}
function tn_Pe(a){_infowindowVersion==2&&tn_Ge.parentNode.replaceChild(tn_Fe,tn_Ge);var b=tn_3d(tn_1,tn_Zd,function(){tn_4d(b);tn_5=tn_b;if(a)window.setTimeout(function(){tn_4=tn_b;tn_Be||tn_Oe(tn_)},500);else{tn_4=tn_b;tn_Be||tn_Oe(tn_)}});tn_1.restore()}function _csi(a,b){var c={};c.sl=a;c.tl=b;var d=window.jstiming.load;d.tick("prt");d.tick("ol");d.name="w";window.jstiming.report(d,c);try{window.external&&window.external.resT()}catch(e){}}
function tn_Me(a,b,c){if(!a)return tn_a;for(var d=[],e=0,f=0;f<c-1;++f){var h=a.indexOf(b,e);if(h==-1)return tn_a;d[f]=a.substring(e,h);e=h+b.length}d[c-1]=a.substring(e);return d}
function tn_Ue(a){if(a=="reload")window.location.reload();else if(a=="restore"){if(tn_8&&tn_He){for(tn_8.style.backgroundColor=tn_He.style.backgroundColor;tn_8.hasChildNodes();)tn_8.removeChild(tn_8.firstChild);for(;tn_He.hasChildNodes();)tn_8.appendChild(tn_He.firstChild);tn_8=tn_a}}else if(tn_2){tn_2.style.backgroundColor=tn_ze;if((a=tn_Me(a,"|",3))&&!tn_$("mt")){tn_8=tn_2;tn_He=tn_2.cloneNode(tn_);for(var b=tn_2.childNodes.length-1;b>=0;--b){var c=tn_2.childNodes[b];c.className!="google-src-text"&&
tn_2.removeChild(c)}b=document.createElement("span");b.className="google-tr-info";b.appendChild(document.createTextNode(a[0]+","+(new Date).getTime()+","+a[1]));tn_2.appendChild(b);c=document.createElement("div");c.innerHTML=a[2];for(b=0;b<c.childNodes.length;++b)tn_2.appendChild(c.childNodes[b].cloneNode(tn_))}tn_4=tn_b;tn_Te();tn_Le()}}function tn_Ve(a){var b=window.onload;window.onload=b?function(){a();b()}:a}var _tipon=tn_Se,_tipoff=tn_Oe,_updatec=tn_Ue,_addload=tn_Ve,tn_We=window.jstiming.load;
tn_We.tick("jl");
